package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"kujicole/domain/model"
)

// RankGroups is the resolver for the rankGroups field.
func (r *intellectualPropertyCategoryResolver) RankGroups(ctx context.Context, obj *model.IntellectualPropertyCategory) ([]*model.IntellectualPropertyRankGroup, error) {
	rankGroups, err := r.UseCases.ListIntellectualPropertyRankGroupsByCategoryID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return rankGroups, nil
}

// IntellectualProperty is the resolver for the intellectualProperty field.
func (r *intellectualPropertyPurchaseHistoryResolver) IntellectualProperty(ctx context.Context, obj *model.IntellectualPropertyPurchaseHistory) (*model.IntellectualProperty, error) {
	property, err := r.UseCases.GetIntellectualPropertyByID(ctx, obj.IntellectualPropertyID)
	if err != nil {
		return nil, err
	}
	return property, nil
}

// PurchaseHistories is the resolver for the purchaseHistories field.
func (r *intellectualPropertyPurchaseTransactionResolver) PurchaseHistories(ctx context.Context, obj *model.IntellectualPropertyPurchaseTransaction) ([]*model.IntellectualPropertyPurchaseHistory, error) {
	purchaseHistories, err := r.UseCases.ListIntellectualPropertyPurchaseHistoriesByPurchaseTransactionID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return purchaseHistories, nil
}

// Properties is the resolver for the properties field.
func (r *intellectualPropertyRankGroupResolver) Properties(ctx context.Context, obj *model.IntellectualPropertyRankGroup) ([]*model.IntellectualProperty, error) {
	properties, err := r.UseCases.ListIntellectualPropertiesByRankGroupID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return properties, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthToken, error) {
	token, err := r.UseCases.Login(ctx, input.MailAddress, input.Password)
	if err != nil {
		return nil, err
	}
	return token, nil
}

// RefreshAccessToken is the resolver for the refreshAccessToken field.
func (r *mutationResolver) RefreshAccessToken(ctx context.Context, input model.RefreshAccessTokenInput) (*model.AuthToken, error) {
	token, err := r.UseCases.RefreshAccessToken(ctx, input.RefreshToken)
	if err != nil {
		return nil, err
	}
	return token, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return false, err
	}
	err = r.UseCases.Logout(ctx, userID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// DrawIntellectualProperty is the resolver for the drawIntellectualProperty field.
func (r *mutationResolver) DrawIntellectualProperty(ctx context.Context, input model.DrawIntellectualPropertyInput) ([]*model.IntellectualProperty, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}
	results, err := r.UseCases.DrawIntellectualProperty(ctx, userID, input)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.UseCases.GetUserByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UseCases.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	return users, nil
}

// IntellectualPropertyCategories is the resolver for the intellectualPropertyCategories field.
func (r *queryResolver) IntellectualPropertyCategories(ctx context.Context) ([]*model.IntellectualPropertyCategory, error) {
	categories, err := r.UseCases.ListIntellectualPropertyCategories(ctx)
	if err != nil {
		return nil, err
	}
	return categories, nil
}

// IntellectualPropertyCategory is the resolver for the intellectualPropertyCategory field.
func (r *queryResolver) IntellectualPropertyCategory(ctx context.Context, ipCategoryID model.ID) (*model.IntellectualPropertyCategory, error) {
	category, err := r.UseCases.GetIntellectualPropertyCategoryByID(ctx, ipCategoryID)
	if err != nil {
		return nil, err
	}
	return category, nil
}

// CheckStock is the resolver for the checkStock field.
func (r *queryResolver) CheckStock(ctx context.Context, input model.CheckStockInput) (*model.CheckStockResult, error) {
	panic(fmt.Errorf("not implemented: CheckStock - checkStock"))
}

// PurchaseTransactions is the resolver for the purchaseTransactions field.
func (r *queryResolver) PurchaseTransactions(ctx context.Context) ([]*model.IntellectualPropertyPurchaseTransaction, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}
	fmt.Println("userID", userID)
	transactions, err := r.UseCases.ListPurchaseTransactionsByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return transactions, nil
}

// IntellectualPropertyCategory returns IntellectualPropertyCategoryResolver implementation.
func (r *Resolver) IntellectualPropertyCategory() IntellectualPropertyCategoryResolver {
	return &intellectualPropertyCategoryResolver{r}
}

// IntellectualPropertyPurchaseHistory returns IntellectualPropertyPurchaseHistoryResolver implementation.
func (r *Resolver) IntellectualPropertyPurchaseHistory() IntellectualPropertyPurchaseHistoryResolver {
	return &intellectualPropertyPurchaseHistoryResolver{r}
}

// IntellectualPropertyPurchaseTransaction returns IntellectualPropertyPurchaseTransactionResolver implementation.
func (r *Resolver) IntellectualPropertyPurchaseTransaction() IntellectualPropertyPurchaseTransactionResolver {
	return &intellectualPropertyPurchaseTransactionResolver{r}
}

// IntellectualPropertyRankGroup returns IntellectualPropertyRankGroupResolver implementation.
func (r *Resolver) IntellectualPropertyRankGroup() IntellectualPropertyRankGroupResolver {
	return &intellectualPropertyRankGroupResolver{r}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type intellectualPropertyCategoryResolver struct{ *Resolver }
type intellectualPropertyPurchaseHistoryResolver struct{ *Resolver }
type intellectualPropertyPurchaseTransactionResolver struct{ *Resolver }
type intellectualPropertyRankGroupResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *intellectualPropertyResolver) RankGroup(ctx context.Context, obj *model.IntellectualProperty) (*model.IntellectualPropertyRankGroup, error) {
	rankGroup, err := r.UseCases.GetRankGroupByID(ctx, obj.IPRankGroupID)
	if err != nil {
		return nil, err
	}
	return rankGroup, nil
}
*/
