package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"kujicole/domain/model"
)

// RankGroups is the resolver for the rankGroups field.
func (r *intellectualPropertyCategoryResolver) RankGroups(ctx context.Context, obj *model.IntellectualPropertyCategory) ([]*model.IntellectualPropertyRankGroup, error) {
	rankGroups, err := r.UseCases.ListIntellectualPropertyRankGroupsByCategoryID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return rankGroups, nil
}

// Properties is the resolver for the properties field.
func (r *intellectualPropertyRankGroupResolver) Properties(ctx context.Context, obj *model.IntellectualPropertyRankGroup) ([]*model.IntellectualProperty, error) {
	properties, err := r.UseCases.ListIntellectualPropertiesByRankGroupID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return properties, nil
}

// DrawIntellectualProperty is the resolver for the drawIntellectualProperty field.
func (r *mutationResolver) DrawIntellectualProperty(ctx context.Context, input model.DrawIntellectualPropertyInput) ([]*model.IntellectualProperty, error) {
	results, err := r.UseCases.DrawIntellectualProperty(ctx, input)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UseCases.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	return users, nil
}

// IntellectualPropertyCategories is the resolver for the intellectualPropertyCategories field.
func (r *queryResolver) IntellectualPropertyCategories(ctx context.Context) ([]*model.IntellectualPropertyCategory, error) {
	categories, err := r.UseCases.ListIntellectualPropertyCategories(ctx)
	if err != nil {
		return nil, err
	}
	return categories, nil
}

// IntellectualPropertyCategory is the resolver for the intellectualPropertyCategory field.
func (r *queryResolver) IntellectualPropertyCategory(ctx context.Context, ipCategoryID model.ID) (*model.IntellectualPropertyCategory, error) {
	panic(fmt.Errorf("not implemented: IntellectualPropertyCategory - intellectualPropertyCategory"))
}

// CheckStock is the resolver for the checkStock field.
func (r *queryResolver) CheckStock(ctx context.Context, input model.CheckStockInput) (*model.CheckStockResult, error) {
	panic(fmt.Errorf("not implemented: CheckStock - checkStock"))
}

// IntellectualPropertyCategory returns IntellectualPropertyCategoryResolver implementation.
func (r *Resolver) IntellectualPropertyCategory() IntellectualPropertyCategoryResolver {
	return &intellectualPropertyCategoryResolver{r}
}

// IntellectualPropertyRankGroup returns IntellectualPropertyRankGroupResolver implementation.
func (r *Resolver) IntellectualPropertyRankGroup() IntellectualPropertyRankGroupResolver {
	return &intellectualPropertyRankGroupResolver{r}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type intellectualPropertyCategoryResolver struct{ *Resolver }
type intellectualPropertyRankGroupResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
