// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"

	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	enums "kujicole/infra/bob/enums"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type Contact runs hooks after queries
var _ bob.HookableType = &Contact{}

// Make sure the type CreditCard runs hooks after queries
var _ bob.HookableType = &CreditCard{}

// Make sure the type IntellectualProperty runs hooks after queries
var _ bob.HookableType = &IntellectualProperty{}

// Make sure the type IntellectualPropertyCategory runs hooks after queries
var _ bob.HookableType = &IntellectualPropertyCategory{}

// Make sure the type IntellectualPropertyRankGroup runs hooks after queries
var _ bob.HookableType = &IntellectualPropertyRankGroup{}

// Make sure the type PurchaseHistory runs hooks after queries
var _ bob.HookableType = &PurchaseHistory{}

// Make sure the type PurchaseTransaction runs hooks after queries
var _ bob.HookableType = &PurchaseTransaction{}

// Make sure the type ShippingAddress runs hooks after queries
var _ bob.HookableType = &ShippingAddress{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type enums.ContactsContactType satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.ContactsContactType)(nil)

// Make sure the type enums.ContactsContactType satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.ContactsContactType)

// Make sure the type decimal.Decimal satisfies database/sql.Scanner
var _ sql.Scanner = (*decimal.Decimal)(nil)

// Make sure the type decimal.Decimal satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(decimal.Decimal)

// Make sure the type enums.IntellectualPropertyRankGroupsRank satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.IntellectualPropertyRankGroupsRank)(nil)

// Make sure the type enums.IntellectualPropertyRankGroupsRank satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.IntellectualPropertyRankGroupsRank)

// Make sure the type enums.PurchaseTransactionsPaymentMethod satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.PurchaseTransactionsPaymentMethod)(nil)

// Make sure the type enums.PurchaseTransactionsPaymentMethod satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.PurchaseTransactionsPaymentMethod)

// Make sure the type enums.PurchaseTransactionsStatus satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.PurchaseTransactionsStatus)(nil)

// Make sure the type enums.PurchaseTransactionsStatus satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.PurchaseTransactionsStatus)

// Make sure the type enums.UsersGender satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.UsersGender)(nil)

// Make sure the type enums.UsersGender satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.UsersGender)
