// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q mysql.Filterable]() struct {
	Contacts                       contactWhere[Q]
	CreditCards                    creditCardWhere[Q]
	IntellectualProperties         intellectualPropertyWhere[Q]
	IntellectualPropertyCategories intellectualPropertyCategoryWhere[Q]
	IntellectualPropertyRankGroups intellectualPropertyRankGroupWhere[Q]
	PurchaseHistories              purchaseHistoryWhere[Q]
	PurchaseTransactions           purchaseTransactionWhere[Q]
	ShippingAddresses              shippingAddressWhere[Q]
	Users                          userWhere[Q]
} {
	return struct {
		Contacts                       contactWhere[Q]
		CreditCards                    creditCardWhere[Q]
		IntellectualProperties         intellectualPropertyWhere[Q]
		IntellectualPropertyCategories intellectualPropertyCategoryWhere[Q]
		IntellectualPropertyRankGroups intellectualPropertyRankGroupWhere[Q]
		PurchaseHistories              purchaseHistoryWhere[Q]
		PurchaseTransactions           purchaseTransactionWhere[Q]
		ShippingAddresses              shippingAddressWhere[Q]
		Users                          userWhere[Q]
	}{
		Contacts:                       buildContactWhere[Q](Contacts.Columns),
		CreditCards:                    buildCreditCardWhere[Q](CreditCards.Columns),
		IntellectualProperties:         buildIntellectualPropertyWhere[Q](IntellectualProperties.Columns),
		IntellectualPropertyCategories: buildIntellectualPropertyCategoryWhere[Q](IntellectualPropertyCategories.Columns),
		IntellectualPropertyRankGroups: buildIntellectualPropertyRankGroupWhere[Q](IntellectualPropertyRankGroups.Columns),
		PurchaseHistories:              buildPurchaseHistoryWhere[Q](PurchaseHistories.Columns),
		PurchaseTransactions:           buildPurchaseTransactionWhere[Q](PurchaseTransactions.Columns),
		ShippingAddresses:              buildShippingAddressWhere[Q](ShippingAddresses.Columns),
		Users:                          buildUserWhere[Q](Users.Columns),
	}
}
