// Code generated by BobGen mysql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	enums "kujicole/infra/bob/enums"
)

// Contact is an object representing the database table.
type Contact struct {
	ID          string                    `db:"id,pk" `
	UserID      string                    `db:"user_id" `
	ContactType enums.ContactsContactType `db:"contact_type" `
	Text        string                    `db:"text" `
	Email       string                    `db:"email" `
	File        null.Val[string]          `db:"file" `
	CreatedAt   time.Time                 `db:"created_at" `
	UpdatedAt   time.Time                 `db:"updated_at" `

	R contactR `db:"-" `
}

// ContactSlice is an alias for a slice of pointers to Contact.
// This should almost always be used instead of []*Contact.
type ContactSlice []*Contact

// Contacts contains methods to work with the contacts table
var Contacts = mysql.NewTablex[*Contact, ContactSlice, *ContactSetter]("contacts", buildContactColumns("contacts"), []string{"id"})

// ContactsQuery is a query on the contacts table
type ContactsQuery = *mysql.ViewQuery[*Contact, ContactSlice]

// contactR is where relationships are stored.
type contactR struct {
	User *User // contacts_ibfk_1
}

func buildContactColumns(alias string) contactColumns {
	return contactColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "contact_type", "text", "email", "file", "created_at", "updated_at",
		).WithParent("contacts"),
		tableAlias:  alias,
		ID:          mysql.Quote(alias, "id"),
		UserID:      mysql.Quote(alias, "user_id"),
		ContactType: mysql.Quote(alias, "contact_type"),
		Text:        mysql.Quote(alias, "text"),
		Email:       mysql.Quote(alias, "email"),
		File:        mysql.Quote(alias, "file"),
		CreatedAt:   mysql.Quote(alias, "created_at"),
		UpdatedAt:   mysql.Quote(alias, "updated_at"),
	}
}

type contactColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          mysql.Expression
	UserID      mysql.Expression
	ContactType mysql.Expression
	Text        mysql.Expression
	Email       mysql.Expression
	File        mysql.Expression
	CreatedAt   mysql.Expression
	UpdatedAt   mysql.Expression
}

func (c contactColumns) Alias() string {
	return c.tableAlias
}

func (contactColumns) AliasedAs(alias string) contactColumns {
	return buildContactColumns(alias)
}

// ContactSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ContactSetter struct {
	ID          omit.Val[string]                    `db:"id,pk" `
	UserID      omit.Val[string]                    `db:"user_id" `
	ContactType omit.Val[enums.ContactsContactType] `db:"contact_type" `
	Text        omit.Val[string]                    `db:"text" `
	Email       omit.Val[string]                    `db:"email" `
	File        omitnull.Val[string]                `db:"file" `
	CreatedAt   omit.Val[time.Time]                 `db:"created_at" `
	UpdatedAt   omit.Val[time.Time]                 `db:"updated_at" `
}

func (s ContactSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.ContactType.IsValue() {
		vals = append(vals, "contact_type")
	}
	if s.Text.IsValue() {
		vals = append(vals, "text")
	}
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if !s.File.IsUnset() {
		vals = append(vals, "file")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ContactSetter) Overwrite(t *Contact) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.ContactType.IsValue() {
		t.ContactType = s.ContactType.MustGet()
	}
	if s.Text.IsValue() {
		t.Text = s.Text.MustGet()
	}
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if !s.File.IsUnset() {
		t.File = s.File.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ContactSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Contacts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UserID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UserID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ContactType.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ContactType.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Text.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Text.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Email.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Email.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.File.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.File.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s ContactSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("contacts")...)
}

func (s ContactSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "user_id")...),
			mysql.Arg(s.UserID),
		}})
	}

	if s.ContactType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "contact_type")...),
			mysql.Arg(s.ContactType),
		}})
	}

	if s.Text.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "text")...),
			mysql.Arg(s.Text),
		}})
	}

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "email")...),
			mysql.Arg(s.Email),
		}})
	}

	if !s.File.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "file")...),
			mysql.Arg(s.File),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindContact retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindContact(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Contact, error) {
	if len(cols) == 0 {
		return Contacts.Query(
			sm.Where(Contacts.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Contacts.Query(
		sm.Where(Contacts.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Contacts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ContactExists checks the presence of a single record by primary key
func ContactExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Contacts.Query(
		sm.Where(Contacts.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Contact is retrieved from the database
func (o *Contact) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Contacts.AfterSelectHooks.RunHooks(ctx, exec, ContactSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Contacts.AfterInsertHooks.RunHooks(ctx, exec, ContactSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Contacts.AfterUpdateHooks.RunHooks(ctx, exec, ContactSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Contacts.AfterDeleteHooks.RunHooks(ctx, exec, ContactSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Contact
func (o *Contact) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Contact) pkEQ() dialect.Expression {
	return mysql.Quote("contacts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Contact
func (o *Contact) Update(ctx context.Context, exec bob.Executor, s *ContactSetter) error {
	_, err := Contacts.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Contact record with an executor
func (o *Contact) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Contacts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Contact using the executor
func (o *Contact) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Contacts.Query(
		sm.Where(Contacts.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ContactSlice is retrieved from the database
func (o ContactSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Contacts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Contacts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Contacts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Contacts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ContactSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("contacts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ContactSlice) copyMatchingRows(from ...*Contact) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ContactSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Contacts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Contact:
				o.copyMatchingRows(retrieved)
			case []*Contact:
				o.copyMatchingRows(retrieved...)
			case ContactSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Contact or a slice of Contact
				// then run the AfterUpdateHooks on the slice
				_, err = Contacts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ContactSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Contacts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Contact:
				o.copyMatchingRows(retrieved)
			case []*Contact:
				o.copyMatchingRows(retrieved...)
			case ContactSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Contact or a slice of Contact
				// then run the AfterDeleteHooks on the slice
				_, err = Contacts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ContactSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ContactSetter) error {
	_, err := Contacts.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o ContactSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Contacts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ContactSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Contacts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *Contact) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(mysql.Arg(o.UserID))),
	)...)
}

func (os ContactSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.UserID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(mysql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachContactUser0(ctx context.Context, exec bob.Executor, count int, contact0 *Contact, user1 *User) (*Contact, error) {
	setter := &ContactSetter{
		UserID: omit.From(user1.ID),
	}

	err := contact0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachContactUser0: %w", err)
	}

	return contact0, nil
}

func (contact0 *Contact) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachContactUser0(ctx, exec, 1, contact0, user1)
	if err != nil {
		return err
	}

	contact0.R.User = user1

	user1.R.Contacts = append(user1.R.Contacts, contact0)

	return nil
}

func (contact0 *Contact) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachContactUser0(ctx, exec, 1, contact0, user1)
	if err != nil {
		return err
	}

	contact0.R.User = user1

	user1.R.Contacts = append(user1.R.Contacts, contact0)

	return nil
}

type contactWhere[Q mysql.Filterable] struct {
	ID          mysql.WhereMod[Q, string]
	UserID      mysql.WhereMod[Q, string]
	ContactType mysql.WhereMod[Q, enums.ContactsContactType]
	Text        mysql.WhereMod[Q, string]
	Email       mysql.WhereMod[Q, string]
	File        mysql.WhereNullMod[Q, string]
	CreatedAt   mysql.WhereMod[Q, time.Time]
	UpdatedAt   mysql.WhereMod[Q, time.Time]
}

func (contactWhere[Q]) AliasedAs(alias string) contactWhere[Q] {
	return buildContactWhere[Q](buildContactColumns(alias))
}

func buildContactWhere[Q mysql.Filterable](cols contactColumns) contactWhere[Q] {
	return contactWhere[Q]{
		ID:          mysql.Where[Q, string](cols.ID),
		UserID:      mysql.Where[Q, string](cols.UserID),
		ContactType: mysql.Where[Q, enums.ContactsContactType](cols.ContactType),
		Text:        mysql.Where[Q, string](cols.Text),
		Email:       mysql.Where[Q, string](cols.Email),
		File:        mysql.WhereNull[Q, string](cols.File),
		CreatedAt:   mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Contact) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("contact cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Contacts = ContactSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("contact has no relationship %q", name)
	}
}

type contactPreloader struct {
	User func(...mysql.PreloadOption) mysql.Preloader
}

func buildContactPreloader() contactPreloader {
	return contactPreloader{
		User: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*User, UserSlice](mysql.PreloadRel{
				Name: "User",
				Sides: []mysql.PreloadSide{
					{
						From:        Contacts,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type contactThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildContactThenLoader[Q orm.Loadable]() contactThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return contactThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the contact's User into the .R struct
func (o *Contact) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Contacts = ContactSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the contact's User into the .R struct
func (os ContactSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Contacts = append(rel.R.Contacts, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type contactJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j contactJoins[Q]) aliasedAs(alias string) contactJoins[Q] {
	return buildContactJoins[Q](buildContactColumns(alias), j.typ)
}

func buildContactJoins[Q dialect.Joinable](cols contactColumns, typ string) contactJoins[Q] {
	return contactJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
