// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// CreditCard is an object representing the database table.
type CreditCard struct {
	ID        string    `db:"id,pk" `
	UserID    string    `db:"user_id" `
	Token     string    `db:"token" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R creditCardR `db:"-" `
}

// CreditCardSlice is an alias for a slice of pointers to CreditCard.
// This should almost always be used instead of []*CreditCard.
type CreditCardSlice []*CreditCard

// CreditCards contains methods to work with the credit_cards table
var CreditCards = mysql.NewTablex[*CreditCard, CreditCardSlice, *CreditCardSetter]("credit_cards", buildCreditCardColumns("credit_cards"), []string{"id"})

// CreditCardsQuery is a query on the credit_cards table
type CreditCardsQuery = *mysql.ViewQuery[*CreditCard, CreditCardSlice]

// creditCardR is where relationships are stored.
type creditCardR struct {
	User *User // credit_cards_ibfk_1
}

func buildCreditCardColumns(alias string) creditCardColumns {
	return creditCardColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "token", "created_at", "updated_at",
		).WithParent("credit_cards"),
		tableAlias: alias,
		ID:         mysql.Quote(alias, "id"),
		UserID:     mysql.Quote(alias, "user_id"),
		Token:      mysql.Quote(alias, "token"),
		CreatedAt:  mysql.Quote(alias, "created_at"),
		UpdatedAt:  mysql.Quote(alias, "updated_at"),
	}
}

type creditCardColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         mysql.Expression
	UserID     mysql.Expression
	Token      mysql.Expression
	CreatedAt  mysql.Expression
	UpdatedAt  mysql.Expression
}

func (c creditCardColumns) Alias() string {
	return c.tableAlias
}

func (creditCardColumns) AliasedAs(alias string) creditCardColumns {
	return buildCreditCardColumns(alias)
}

// CreditCardSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CreditCardSetter struct {
	ID        omit.Val[string]    `db:"id,pk" `
	UserID    omit.Val[string]    `db:"user_id" `
	Token     omit.Val[string]    `db:"token" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s CreditCardSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Token.IsValue() {
		vals = append(vals, "token")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s CreditCardSetter) Overwrite(t *CreditCard) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Token.IsValue() {
		t.Token = s.Token.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *CreditCardSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return CreditCards.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UserID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UserID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Token.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Token.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s CreditCardSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("credit_cards")...)
}

func (s CreditCardSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "user_id")...),
			mysql.Arg(s.UserID),
		}})
	}

	if s.Token.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "token")...),
			mysql.Arg(s.Token),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindCreditCard retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCreditCard(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*CreditCard, error) {
	if len(cols) == 0 {
		return CreditCards.Query(
			sm.Where(CreditCards.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return CreditCards.Query(
		sm.Where(CreditCards.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(CreditCards.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CreditCardExists checks the presence of a single record by primary key
func CreditCardExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return CreditCards.Query(
		sm.Where(CreditCards.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after CreditCard is retrieved from the database
func (o *CreditCard) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CreditCards.AfterSelectHooks.RunHooks(ctx, exec, CreditCardSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = CreditCards.AfterInsertHooks.RunHooks(ctx, exec, CreditCardSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = CreditCards.AfterUpdateHooks.RunHooks(ctx, exec, CreditCardSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = CreditCards.AfterDeleteHooks.RunHooks(ctx, exec, CreditCardSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the CreditCard
func (o *CreditCard) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *CreditCard) pkEQ() dialect.Expression {
	return mysql.Quote("credit_cards", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the CreditCard
func (o *CreditCard) Update(ctx context.Context, exec bob.Executor, s *CreditCardSetter) error {
	_, err := CreditCards.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single CreditCard record with an executor
func (o *CreditCard) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := CreditCards.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the CreditCard using the executor
func (o *CreditCard) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := CreditCards.Query(
		sm.Where(CreditCards.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CreditCardSlice is retrieved from the database
func (o CreditCardSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CreditCards.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = CreditCards.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = CreditCards.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = CreditCards.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CreditCardSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("credit_cards", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CreditCardSlice) copyMatchingRows(from ...*CreditCard) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CreditCardSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CreditCards.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CreditCard:
				o.copyMatchingRows(retrieved)
			case []*CreditCard:
				o.copyMatchingRows(retrieved...)
			case CreditCardSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CreditCard or a slice of CreditCard
				// then run the AfterUpdateHooks on the slice
				_, err = CreditCards.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CreditCardSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CreditCards.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CreditCard:
				o.copyMatchingRows(retrieved)
			case []*CreditCard:
				o.copyMatchingRows(retrieved...)
			case CreditCardSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CreditCard or a slice of CreditCard
				// then run the AfterDeleteHooks on the slice
				_, err = CreditCards.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CreditCardSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CreditCardSetter) error {
	_, err := CreditCards.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o CreditCardSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CreditCards.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CreditCardSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := CreditCards.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *CreditCard) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(mysql.Arg(o.UserID))),
	)...)
}

func (os CreditCardSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.UserID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(mysql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachCreditCardUser0(ctx context.Context, exec bob.Executor, count int, creditCard0 *CreditCard, user1 *User) (*CreditCard, error) {
	setter := &CreditCardSetter{
		UserID: omit.From(user1.ID),
	}

	err := creditCard0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCreditCardUser0: %w", err)
	}

	return creditCard0, nil
}

func (creditCard0 *CreditCard) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCreditCardUser0(ctx, exec, 1, creditCard0, user1)
	if err != nil {
		return err
	}

	creditCard0.R.User = user1

	user1.R.CreditCards = append(user1.R.CreditCards, creditCard0)

	return nil
}

func (creditCard0 *CreditCard) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachCreditCardUser0(ctx, exec, 1, creditCard0, user1)
	if err != nil {
		return err
	}

	creditCard0.R.User = user1

	user1.R.CreditCards = append(user1.R.CreditCards, creditCard0)

	return nil
}

type creditCardWhere[Q mysql.Filterable] struct {
	ID        mysql.WhereMod[Q, string]
	UserID    mysql.WhereMod[Q, string]
	Token     mysql.WhereMod[Q, string]
	CreatedAt mysql.WhereMod[Q, time.Time]
	UpdatedAt mysql.WhereMod[Q, time.Time]
}

func (creditCardWhere[Q]) AliasedAs(alias string) creditCardWhere[Q] {
	return buildCreditCardWhere[Q](buildCreditCardColumns(alias))
}

func buildCreditCardWhere[Q mysql.Filterable](cols creditCardColumns) creditCardWhere[Q] {
	return creditCardWhere[Q]{
		ID:        mysql.Where[Q, string](cols.ID),
		UserID:    mysql.Where[Q, string](cols.UserID),
		Token:     mysql.Where[Q, string](cols.Token),
		CreatedAt: mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *CreditCard) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("creditCard cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.CreditCards = CreditCardSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("creditCard has no relationship %q", name)
	}
}

type creditCardPreloader struct {
	User func(...mysql.PreloadOption) mysql.Preloader
}

func buildCreditCardPreloader() creditCardPreloader {
	return creditCardPreloader{
		User: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*User, UserSlice](mysql.PreloadRel{
				Name: "User",
				Sides: []mysql.PreloadSide{
					{
						From:        CreditCards,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type creditCardThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCreditCardThenLoader[Q orm.Loadable]() creditCardThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return creditCardThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the creditCard's User into the .R struct
func (o *CreditCard) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CreditCards = CreditCardSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the creditCard's User into the .R struct
func (os CreditCardSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.CreditCards = append(rel.R.CreditCards, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type creditCardJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j creditCardJoins[Q]) aliasedAs(alias string) creditCardJoins[Q] {
	return buildCreditCardJoins[Q](buildCreditCardColumns(alias), j.typ)
}

func buildCreditCardJoins[Q dialect.Joinable](cols creditCardColumns, typ string) creditCardJoins[Q] {
	return creditCardJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
