// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// IntellectualPropertyCategory is an object representing the database table.
type IntellectualPropertyCategory struct {
	ID             string           `db:"id,pk" `
	Name           string           `db:"name" `
	Price          decimal.Decimal  `db:"price" `
	SalesStartDate time.Time        `db:"sales_start_date" `
	SalesEndDate   time.Time        `db:"sales_end_date" `
	Fee            decimal.Decimal  `db:"fee" `
	Precautions    null.Val[string] `db:"precautions" `
	IsHidden       bool             `db:"is_hidden" `
	ImgURL         null.Val[string] `db:"img_url" `
	CreatedAt      time.Time        `db:"created_at" `
	UpdatedAt      time.Time        `db:"updated_at" `

	R intellectualPropertyCategoryR `db:"-" `
}

// IntellectualPropertyCategorySlice is an alias for a slice of pointers to IntellectualPropertyCategory.
// This should almost always be used instead of []*IntellectualPropertyCategory.
type IntellectualPropertyCategorySlice []*IntellectualPropertyCategory

// IntellectualPropertyCategories contains methods to work with the intellectual_property_categories table
var IntellectualPropertyCategories = mysql.NewTablex[*IntellectualPropertyCategory, IntellectualPropertyCategorySlice, *IntellectualPropertyCategorySetter]("intellectual_property_categories", buildIntellectualPropertyCategoryColumns("intellectual_property_categories"), []string{"id"})

// IntellectualPropertyCategoriesQuery is a query on the intellectual_property_categories table
type IntellectualPropertyCategoriesQuery = *mysql.ViewQuery[*IntellectualPropertyCategory, IntellectualPropertyCategorySlice]

// intellectualPropertyCategoryR is where relationships are stored.
type intellectualPropertyCategoryR struct {
	IPCategoryIntellectualPropertyRankGroups IntellectualPropertyRankGroupSlice // intellectual_property_rank_groups_ibfk_1
	IPCategoryPurchaseTransactions           PurchaseTransactionSlice           // purchase_transactions_ibfk_2
}

func buildIntellectualPropertyCategoryColumns(alias string) intellectualPropertyCategoryColumns {
	return intellectualPropertyCategoryColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "price", "sales_start_date", "sales_end_date", "fee", "precautions", "is_hidden", "img_url", "created_at", "updated_at",
		).WithParent("intellectual_property_categories"),
		tableAlias:     alias,
		ID:             mysql.Quote(alias, "id"),
		Name:           mysql.Quote(alias, "name"),
		Price:          mysql.Quote(alias, "price"),
		SalesStartDate: mysql.Quote(alias, "sales_start_date"),
		SalesEndDate:   mysql.Quote(alias, "sales_end_date"),
		Fee:            mysql.Quote(alias, "fee"),
		Precautions:    mysql.Quote(alias, "precautions"),
		IsHidden:       mysql.Quote(alias, "is_hidden"),
		ImgURL:         mysql.Quote(alias, "img_url"),
		CreatedAt:      mysql.Quote(alias, "created_at"),
		UpdatedAt:      mysql.Quote(alias, "updated_at"),
	}
}

type intellectualPropertyCategoryColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             mysql.Expression
	Name           mysql.Expression
	Price          mysql.Expression
	SalesStartDate mysql.Expression
	SalesEndDate   mysql.Expression
	Fee            mysql.Expression
	Precautions    mysql.Expression
	IsHidden       mysql.Expression
	ImgURL         mysql.Expression
	CreatedAt      mysql.Expression
	UpdatedAt      mysql.Expression
}

func (c intellectualPropertyCategoryColumns) Alias() string {
	return c.tableAlias
}

func (intellectualPropertyCategoryColumns) AliasedAs(alias string) intellectualPropertyCategoryColumns {
	return buildIntellectualPropertyCategoryColumns(alias)
}

// IntellectualPropertyCategorySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type IntellectualPropertyCategorySetter struct {
	ID             omit.Val[string]          `db:"id,pk" `
	Name           omit.Val[string]          `db:"name" `
	Price          omit.Val[decimal.Decimal] `db:"price" `
	SalesStartDate omit.Val[time.Time]       `db:"sales_start_date" `
	SalesEndDate   omit.Val[time.Time]       `db:"sales_end_date" `
	Fee            omit.Val[decimal.Decimal] `db:"fee" `
	Precautions    omitnull.Val[string]      `db:"precautions" `
	IsHidden       omit.Val[bool]            `db:"is_hidden" `
	ImgURL         omitnull.Val[string]      `db:"img_url" `
	CreatedAt      omit.Val[time.Time]       `db:"created_at" `
	UpdatedAt      omit.Val[time.Time]       `db:"updated_at" `
}

func (s IntellectualPropertyCategorySetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Price.IsValue() {
		vals = append(vals, "price")
	}
	if s.SalesStartDate.IsValue() {
		vals = append(vals, "sales_start_date")
	}
	if s.SalesEndDate.IsValue() {
		vals = append(vals, "sales_end_date")
	}
	if s.Fee.IsValue() {
		vals = append(vals, "fee")
	}
	if !s.Precautions.IsUnset() {
		vals = append(vals, "precautions")
	}
	if s.IsHidden.IsValue() {
		vals = append(vals, "is_hidden")
	}
	if !s.ImgURL.IsUnset() {
		vals = append(vals, "img_url")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s IntellectualPropertyCategorySetter) Overwrite(t *IntellectualPropertyCategory) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Price.IsValue() {
		t.Price = s.Price.MustGet()
	}
	if s.SalesStartDate.IsValue() {
		t.SalesStartDate = s.SalesStartDate.MustGet()
	}
	if s.SalesEndDate.IsValue() {
		t.SalesEndDate = s.SalesEndDate.MustGet()
	}
	if s.Fee.IsValue() {
		t.Fee = s.Fee.MustGet()
	}
	if !s.Precautions.IsUnset() {
		t.Precautions = s.Precautions.MustGetNull()
	}
	if s.IsHidden.IsValue() {
		t.IsHidden = s.IsHidden.MustGet()
	}
	if !s.ImgURL.IsUnset() {
		t.ImgURL = s.ImgURL.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *IntellectualPropertyCategorySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return IntellectualPropertyCategories.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Price.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Price.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.SalesStartDate.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.SalesStartDate.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.SalesEndDate.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.SalesEndDate.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Fee.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Fee.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.Precautions.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Precautions.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IsHidden.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IsHidden.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.ImgURL.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ImgURL.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s IntellectualPropertyCategorySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("intellectual_property_categories")...)
}

func (s IntellectualPropertyCategorySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.Price.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "price")...),
			mysql.Arg(s.Price),
		}})
	}

	if s.SalesStartDate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "sales_start_date")...),
			mysql.Arg(s.SalesStartDate),
		}})
	}

	if s.SalesEndDate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "sales_end_date")...),
			mysql.Arg(s.SalesEndDate),
		}})
	}

	if s.Fee.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "fee")...),
			mysql.Arg(s.Fee),
		}})
	}

	if !s.Precautions.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "precautions")...),
			mysql.Arg(s.Precautions),
		}})
	}

	if s.IsHidden.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "is_hidden")...),
			mysql.Arg(s.IsHidden),
		}})
	}

	if !s.ImgURL.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "img_url")...),
			mysql.Arg(s.ImgURL),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindIntellectualPropertyCategory retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindIntellectualPropertyCategory(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*IntellectualPropertyCategory, error) {
	if len(cols) == 0 {
		return IntellectualPropertyCategories.Query(
			sm.Where(IntellectualPropertyCategories.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return IntellectualPropertyCategories.Query(
		sm.Where(IntellectualPropertyCategories.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(IntellectualPropertyCategories.Columns.Only(cols...)),
	).One(ctx, exec)
}

// IntellectualPropertyCategoryExists checks the presence of a single record by primary key
func IntellectualPropertyCategoryExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return IntellectualPropertyCategories.Query(
		sm.Where(IntellectualPropertyCategories.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after IntellectualPropertyCategory is retrieved from the database
func (o *IntellectualPropertyCategory) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = IntellectualPropertyCategories.AfterSelectHooks.RunHooks(ctx, exec, IntellectualPropertyCategorySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = IntellectualPropertyCategories.AfterInsertHooks.RunHooks(ctx, exec, IntellectualPropertyCategorySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = IntellectualPropertyCategories.AfterUpdateHooks.RunHooks(ctx, exec, IntellectualPropertyCategorySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = IntellectualPropertyCategories.AfterDeleteHooks.RunHooks(ctx, exec, IntellectualPropertyCategorySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the IntellectualPropertyCategory
func (o *IntellectualPropertyCategory) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *IntellectualPropertyCategory) pkEQ() dialect.Expression {
	return mysql.Quote("intellectual_property_categories", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the IntellectualPropertyCategory
func (o *IntellectualPropertyCategory) Update(ctx context.Context, exec bob.Executor, s *IntellectualPropertyCategorySetter) error {
	_, err := IntellectualPropertyCategories.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single IntellectualPropertyCategory record with an executor
func (o *IntellectualPropertyCategory) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := IntellectualPropertyCategories.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the IntellectualPropertyCategory using the executor
func (o *IntellectualPropertyCategory) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := IntellectualPropertyCategories.Query(
		sm.Where(IntellectualPropertyCategories.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after IntellectualPropertyCategorySlice is retrieved from the database
func (o IntellectualPropertyCategorySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = IntellectualPropertyCategories.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = IntellectualPropertyCategories.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = IntellectualPropertyCategories.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = IntellectualPropertyCategories.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o IntellectualPropertyCategorySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("intellectual_property_categories", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o IntellectualPropertyCategorySlice) copyMatchingRows(from ...*IntellectualPropertyCategory) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o IntellectualPropertyCategorySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return IntellectualPropertyCategories.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *IntellectualPropertyCategory:
				o.copyMatchingRows(retrieved)
			case []*IntellectualPropertyCategory:
				o.copyMatchingRows(retrieved...)
			case IntellectualPropertyCategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a IntellectualPropertyCategory or a slice of IntellectualPropertyCategory
				// then run the AfterUpdateHooks on the slice
				_, err = IntellectualPropertyCategories.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o IntellectualPropertyCategorySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return IntellectualPropertyCategories.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *IntellectualPropertyCategory:
				o.copyMatchingRows(retrieved)
			case []*IntellectualPropertyCategory:
				o.copyMatchingRows(retrieved...)
			case IntellectualPropertyCategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a IntellectualPropertyCategory or a slice of IntellectualPropertyCategory
				// then run the AfterDeleteHooks on the slice
				_, err = IntellectualPropertyCategories.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o IntellectualPropertyCategorySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals IntellectualPropertyCategorySetter) error {
	_, err := IntellectualPropertyCategories.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o IntellectualPropertyCategorySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := IntellectualPropertyCategories.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o IntellectualPropertyCategorySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := IntellectualPropertyCategories.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// IPCategoryIntellectualPropertyRankGroups starts a query for related objects on intellectual_property_rank_groups
func (o *IntellectualPropertyCategory) IPCategoryIntellectualPropertyRankGroups(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertyRankGroupsQuery {
	return IntellectualPropertyRankGroups.Query(append(mods,
		sm.Where(IntellectualPropertyRankGroups.Columns.IPCategoryID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os IntellectualPropertyCategorySlice) IPCategoryIntellectualPropertyRankGroups(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertyRankGroupsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return IntellectualPropertyRankGroups.Query(append(mods,
		sm.Where(mysql.Group(IntellectualPropertyRankGroups.Columns.IPCategoryID).OP("IN", PKArgExpr)),
	)...)
}

// IPCategoryPurchaseTransactions starts a query for related objects on purchase_transactions
func (o *IntellectualPropertyCategory) IPCategoryPurchaseTransactions(mods ...bob.Mod[*dialect.SelectQuery]) PurchaseTransactionsQuery {
	return PurchaseTransactions.Query(append(mods,
		sm.Where(PurchaseTransactions.Columns.IPCategoryID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os IntellectualPropertyCategorySlice) IPCategoryPurchaseTransactions(mods ...bob.Mod[*dialect.SelectQuery]) PurchaseTransactionsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return PurchaseTransactions.Query(append(mods,
		sm.Where(mysql.Group(PurchaseTransactions.Columns.IPCategoryID).OP("IN", PKArgExpr)),
	)...)
}

func insertIntellectualPropertyCategoryIPCategoryIntellectualPropertyRankGroups0(ctx context.Context, exec bob.Executor, intellectualPropertyRankGroups1 []*IntellectualPropertyRankGroupSetter, intellectualPropertyCategory0 *IntellectualPropertyCategory) (IntellectualPropertyRankGroupSlice, error) {
	for i := range intellectualPropertyRankGroups1 {
		intellectualPropertyRankGroups1[i].IPCategoryID = omit.From(intellectualPropertyCategory0.ID)
	}

	ret, err := IntellectualPropertyRankGroups.Insert(bob.ToMods(intellectualPropertyRankGroups1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertIntellectualPropertyCategoryIPCategoryIntellectualPropertyRankGroups0: %w", err)
	}

	return ret, nil
}

func attachIntellectualPropertyCategoryIPCategoryIntellectualPropertyRankGroups0(ctx context.Context, exec bob.Executor, count int, intellectualPropertyRankGroups1 IntellectualPropertyRankGroupSlice, intellectualPropertyCategory0 *IntellectualPropertyCategory) (IntellectualPropertyRankGroupSlice, error) {
	setter := &IntellectualPropertyRankGroupSetter{
		IPCategoryID: omit.From(intellectualPropertyCategory0.ID),
	}

	err := intellectualPropertyRankGroups1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachIntellectualPropertyCategoryIPCategoryIntellectualPropertyRankGroups0: %w", err)
	}

	return intellectualPropertyRankGroups1, nil
}

func (intellectualPropertyCategory0 *IntellectualPropertyCategory) InsertIPCategoryIntellectualPropertyRankGroups(ctx context.Context, exec bob.Executor, related ...*IntellectualPropertyRankGroupSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	intellectualPropertyRankGroups1, err := insertIntellectualPropertyCategoryIPCategoryIntellectualPropertyRankGroups0(ctx, exec, related, intellectualPropertyCategory0)
	if err != nil {
		return err
	}

	intellectualPropertyCategory0.R.IPCategoryIntellectualPropertyRankGroups = append(intellectualPropertyCategory0.R.IPCategoryIntellectualPropertyRankGroups, intellectualPropertyRankGroups1...)

	for _, rel := range intellectualPropertyRankGroups1 {
		rel.R.IPCategoryIntellectualPropertyCategory = intellectualPropertyCategory0
	}
	return nil
}

func (intellectualPropertyCategory0 *IntellectualPropertyCategory) AttachIPCategoryIntellectualPropertyRankGroups(ctx context.Context, exec bob.Executor, related ...*IntellectualPropertyRankGroup) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	intellectualPropertyRankGroups1 := IntellectualPropertyRankGroupSlice(related)

	_, err = attachIntellectualPropertyCategoryIPCategoryIntellectualPropertyRankGroups0(ctx, exec, len(related), intellectualPropertyRankGroups1, intellectualPropertyCategory0)
	if err != nil {
		return err
	}

	intellectualPropertyCategory0.R.IPCategoryIntellectualPropertyRankGroups = append(intellectualPropertyCategory0.R.IPCategoryIntellectualPropertyRankGroups, intellectualPropertyRankGroups1...)

	for _, rel := range related {
		rel.R.IPCategoryIntellectualPropertyCategory = intellectualPropertyCategory0
	}

	return nil
}

func insertIntellectualPropertyCategoryIPCategoryPurchaseTransactions0(ctx context.Context, exec bob.Executor, purchaseTransactions1 []*PurchaseTransactionSetter, intellectualPropertyCategory0 *IntellectualPropertyCategory) (PurchaseTransactionSlice, error) {
	for i := range purchaseTransactions1 {
		purchaseTransactions1[i].IPCategoryID = omit.From(intellectualPropertyCategory0.ID)
	}

	ret, err := PurchaseTransactions.Insert(bob.ToMods(purchaseTransactions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertIntellectualPropertyCategoryIPCategoryPurchaseTransactions0: %w", err)
	}

	return ret, nil
}

func attachIntellectualPropertyCategoryIPCategoryPurchaseTransactions0(ctx context.Context, exec bob.Executor, count int, purchaseTransactions1 PurchaseTransactionSlice, intellectualPropertyCategory0 *IntellectualPropertyCategory) (PurchaseTransactionSlice, error) {
	setter := &PurchaseTransactionSetter{
		IPCategoryID: omit.From(intellectualPropertyCategory0.ID),
	}

	err := purchaseTransactions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachIntellectualPropertyCategoryIPCategoryPurchaseTransactions0: %w", err)
	}

	return purchaseTransactions1, nil
}

func (intellectualPropertyCategory0 *IntellectualPropertyCategory) InsertIPCategoryPurchaseTransactions(ctx context.Context, exec bob.Executor, related ...*PurchaseTransactionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	purchaseTransactions1, err := insertIntellectualPropertyCategoryIPCategoryPurchaseTransactions0(ctx, exec, related, intellectualPropertyCategory0)
	if err != nil {
		return err
	}

	intellectualPropertyCategory0.R.IPCategoryPurchaseTransactions = append(intellectualPropertyCategory0.R.IPCategoryPurchaseTransactions, purchaseTransactions1...)

	for _, rel := range purchaseTransactions1 {
		rel.R.IPCategoryIntellectualPropertyCategory = intellectualPropertyCategory0
	}
	return nil
}

func (intellectualPropertyCategory0 *IntellectualPropertyCategory) AttachIPCategoryPurchaseTransactions(ctx context.Context, exec bob.Executor, related ...*PurchaseTransaction) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	purchaseTransactions1 := PurchaseTransactionSlice(related)

	_, err = attachIntellectualPropertyCategoryIPCategoryPurchaseTransactions0(ctx, exec, len(related), purchaseTransactions1, intellectualPropertyCategory0)
	if err != nil {
		return err
	}

	intellectualPropertyCategory0.R.IPCategoryPurchaseTransactions = append(intellectualPropertyCategory0.R.IPCategoryPurchaseTransactions, purchaseTransactions1...)

	for _, rel := range related {
		rel.R.IPCategoryIntellectualPropertyCategory = intellectualPropertyCategory0
	}

	return nil
}

type intellectualPropertyCategoryWhere[Q mysql.Filterable] struct {
	ID             mysql.WhereMod[Q, string]
	Name           mysql.WhereMod[Q, string]
	Price          mysql.WhereMod[Q, decimal.Decimal]
	SalesStartDate mysql.WhereMod[Q, time.Time]
	SalesEndDate   mysql.WhereMod[Q, time.Time]
	Fee            mysql.WhereMod[Q, decimal.Decimal]
	Precautions    mysql.WhereNullMod[Q, string]
	IsHidden       mysql.WhereMod[Q, bool]
	ImgURL         mysql.WhereNullMod[Q, string]
	CreatedAt      mysql.WhereMod[Q, time.Time]
	UpdatedAt      mysql.WhereMod[Q, time.Time]
}

func (intellectualPropertyCategoryWhere[Q]) AliasedAs(alias string) intellectualPropertyCategoryWhere[Q] {
	return buildIntellectualPropertyCategoryWhere[Q](buildIntellectualPropertyCategoryColumns(alias))
}

func buildIntellectualPropertyCategoryWhere[Q mysql.Filterable](cols intellectualPropertyCategoryColumns) intellectualPropertyCategoryWhere[Q] {
	return intellectualPropertyCategoryWhere[Q]{
		ID:             mysql.Where[Q, string](cols.ID),
		Name:           mysql.Where[Q, string](cols.Name),
		Price:          mysql.Where[Q, decimal.Decimal](cols.Price),
		SalesStartDate: mysql.Where[Q, time.Time](cols.SalesStartDate),
		SalesEndDate:   mysql.Where[Q, time.Time](cols.SalesEndDate),
		Fee:            mysql.Where[Q, decimal.Decimal](cols.Fee),
		Precautions:    mysql.WhereNull[Q, string](cols.Precautions),
		IsHidden:       mysql.Where[Q, bool](cols.IsHidden),
		ImgURL:         mysql.WhereNull[Q, string](cols.ImgURL),
		CreatedAt:      mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:      mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *IntellectualPropertyCategory) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "IPCategoryIntellectualPropertyRankGroups":
		rels, ok := retrieved.(IntellectualPropertyRankGroupSlice)
		if !ok {
			return fmt.Errorf("intellectualPropertyCategory cannot load %T as %q", retrieved, name)
		}

		o.R.IPCategoryIntellectualPropertyRankGroups = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.IPCategoryIntellectualPropertyCategory = o
			}
		}
		return nil
	case "IPCategoryPurchaseTransactions":
		rels, ok := retrieved.(PurchaseTransactionSlice)
		if !ok {
			return fmt.Errorf("intellectualPropertyCategory cannot load %T as %q", retrieved, name)
		}

		o.R.IPCategoryPurchaseTransactions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.IPCategoryIntellectualPropertyCategory = o
			}
		}
		return nil
	default:
		return fmt.Errorf("intellectualPropertyCategory has no relationship %q", name)
	}
}

type intellectualPropertyCategoryPreloader struct{}

func buildIntellectualPropertyCategoryPreloader() intellectualPropertyCategoryPreloader {
	return intellectualPropertyCategoryPreloader{}
}

type intellectualPropertyCategoryThenLoader[Q orm.Loadable] struct {
	IPCategoryIntellectualPropertyRankGroups func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	IPCategoryPurchaseTransactions           func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildIntellectualPropertyCategoryThenLoader[Q orm.Loadable]() intellectualPropertyCategoryThenLoader[Q] {
	type IPCategoryIntellectualPropertyRankGroupsLoadInterface interface {
		LoadIPCategoryIntellectualPropertyRankGroups(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type IPCategoryPurchaseTransactionsLoadInterface interface {
		LoadIPCategoryPurchaseTransactions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return intellectualPropertyCategoryThenLoader[Q]{
		IPCategoryIntellectualPropertyRankGroups: thenLoadBuilder[Q](
			"IPCategoryIntellectualPropertyRankGroups",
			func(ctx context.Context, exec bob.Executor, retrieved IPCategoryIntellectualPropertyRankGroupsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadIPCategoryIntellectualPropertyRankGroups(ctx, exec, mods...)
			},
		),
		IPCategoryPurchaseTransactions: thenLoadBuilder[Q](
			"IPCategoryPurchaseTransactions",
			func(ctx context.Context, exec bob.Executor, retrieved IPCategoryPurchaseTransactionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadIPCategoryPurchaseTransactions(ctx, exec, mods...)
			},
		),
	}
}

// LoadIPCategoryIntellectualPropertyRankGroups loads the intellectualPropertyCategory's IPCategoryIntellectualPropertyRankGroups into the .R struct
func (o *IntellectualPropertyCategory) LoadIPCategoryIntellectualPropertyRankGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IPCategoryIntellectualPropertyRankGroups = nil

	related, err := o.IPCategoryIntellectualPropertyRankGroups(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.IPCategoryIntellectualPropertyCategory = o
	}

	o.R.IPCategoryIntellectualPropertyRankGroups = related
	return nil
}

// LoadIPCategoryIntellectualPropertyRankGroups loads the intellectualPropertyCategory's IPCategoryIntellectualPropertyRankGroups into the .R struct
func (os IntellectualPropertyCategorySlice) LoadIPCategoryIntellectualPropertyRankGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	intellectualPropertyRankGroups, err := os.IPCategoryIntellectualPropertyRankGroups(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.IPCategoryIntellectualPropertyRankGroups = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range intellectualPropertyRankGroups {

			if !(o.ID == rel.IPCategoryID) {
				continue
			}

			rel.R.IPCategoryIntellectualPropertyCategory = o

			o.R.IPCategoryIntellectualPropertyRankGroups = append(o.R.IPCategoryIntellectualPropertyRankGroups, rel)
		}
	}

	return nil
}

// LoadIPCategoryPurchaseTransactions loads the intellectualPropertyCategory's IPCategoryPurchaseTransactions into the .R struct
func (o *IntellectualPropertyCategory) LoadIPCategoryPurchaseTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IPCategoryPurchaseTransactions = nil

	related, err := o.IPCategoryPurchaseTransactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.IPCategoryIntellectualPropertyCategory = o
	}

	o.R.IPCategoryPurchaseTransactions = related
	return nil
}

// LoadIPCategoryPurchaseTransactions loads the intellectualPropertyCategory's IPCategoryPurchaseTransactions into the .R struct
func (os IntellectualPropertyCategorySlice) LoadIPCategoryPurchaseTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	purchaseTransactions, err := os.IPCategoryPurchaseTransactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.IPCategoryPurchaseTransactions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range purchaseTransactions {

			if !(o.ID == rel.IPCategoryID) {
				continue
			}

			rel.R.IPCategoryIntellectualPropertyCategory = o

			o.R.IPCategoryPurchaseTransactions = append(o.R.IPCategoryPurchaseTransactions, rel)
		}
	}

	return nil
}

type intellectualPropertyCategoryJoins[Q dialect.Joinable] struct {
	typ                                      string
	IPCategoryIntellectualPropertyRankGroups modAs[Q, intellectualPropertyRankGroupColumns]
	IPCategoryPurchaseTransactions           modAs[Q, purchaseTransactionColumns]
}

func (j intellectualPropertyCategoryJoins[Q]) aliasedAs(alias string) intellectualPropertyCategoryJoins[Q] {
	return buildIntellectualPropertyCategoryJoins[Q](buildIntellectualPropertyCategoryColumns(alias), j.typ)
}

func buildIntellectualPropertyCategoryJoins[Q dialect.Joinable](cols intellectualPropertyCategoryColumns, typ string) intellectualPropertyCategoryJoins[Q] {
	return intellectualPropertyCategoryJoins[Q]{
		typ: typ,
		IPCategoryIntellectualPropertyRankGroups: modAs[Q, intellectualPropertyRankGroupColumns]{
			c: IntellectualPropertyRankGroups.Columns,
			f: func(to intellectualPropertyRankGroupColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, IntellectualPropertyRankGroups.Name().As(to.Alias())).On(
						to.IPCategoryID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		IPCategoryPurchaseTransactions: modAs[Q, purchaseTransactionColumns]{
			c: PurchaseTransactions.Columns,
			f: func(to purchaseTransactionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PurchaseTransactions.Name().As(to.Alias())).On(
						to.IPCategoryID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
