// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// IntellectualProperty is an object representing the database table.
type IntellectualProperty struct {
	ID            string           `db:"id,pk" `
	IPRankGroupID string           `db:"ip_rank_group_id" `
	Name          string           `db:"name" `
	Stock         int32            `db:"stock" `
	IsHidden      bool             `db:"is_hidden" `
	ImgURL        null.Val[string] `db:"img_url" `
	CreatedAt     time.Time        `db:"created_at" `
	UpdatedAt     time.Time        `db:"updated_at" `

	R intellectualPropertyR `db:"-" `
}

// IntellectualPropertySlice is an alias for a slice of pointers to IntellectualProperty.
// This should almost always be used instead of []*IntellectualProperty.
type IntellectualPropertySlice []*IntellectualProperty

// IntellectualProperties contains methods to work with the intellectual_properties table
var IntellectualProperties = mysql.NewTablex[*IntellectualProperty, IntellectualPropertySlice, *IntellectualPropertySetter]("intellectual_properties", buildIntellectualPropertyColumns("intellectual_properties"), []string{"id"})

// IntellectualPropertiesQuery is a query on the intellectual_properties table
type IntellectualPropertiesQuery = *mysql.ViewQuery[*IntellectualProperty, IntellectualPropertySlice]

// intellectualPropertyR is where relationships are stored.
type intellectualPropertyR struct {
	IPRankGroupIntellectualPropertyRankGroup *IntellectualPropertyRankGroup // intellectual_properties_ibfk_1
	IDPurchaseHistories                      PurchaseHistorySlice           // purchase_histories_ibfk_2
}

func buildIntellectualPropertyColumns(alias string) intellectualPropertyColumns {
	return intellectualPropertyColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "ip_rank_group_id", "name", "stock", "is_hidden", "img_url", "created_at", "updated_at",
		).WithParent("intellectual_properties"),
		tableAlias:    alias,
		ID:            mysql.Quote(alias, "id"),
		IPRankGroupID: mysql.Quote(alias, "ip_rank_group_id"),
		Name:          mysql.Quote(alias, "name"),
		Stock:         mysql.Quote(alias, "stock"),
		IsHidden:      mysql.Quote(alias, "is_hidden"),
		ImgURL:        mysql.Quote(alias, "img_url"),
		CreatedAt:     mysql.Quote(alias, "created_at"),
		UpdatedAt:     mysql.Quote(alias, "updated_at"),
	}
}

type intellectualPropertyColumns struct {
	expr.ColumnsExpr
	tableAlias    string
	ID            mysql.Expression
	IPRankGroupID mysql.Expression
	Name          mysql.Expression
	Stock         mysql.Expression
	IsHidden      mysql.Expression
	ImgURL        mysql.Expression
	CreatedAt     mysql.Expression
	UpdatedAt     mysql.Expression
}

func (c intellectualPropertyColumns) Alias() string {
	return c.tableAlias
}

func (intellectualPropertyColumns) AliasedAs(alias string) intellectualPropertyColumns {
	return buildIntellectualPropertyColumns(alias)
}

// IntellectualPropertySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type IntellectualPropertySetter struct {
	ID            omit.Val[string]     `db:"id,pk" `
	IPRankGroupID omit.Val[string]     `db:"ip_rank_group_id" `
	Name          omit.Val[string]     `db:"name" `
	Stock         omit.Val[int32]      `db:"stock" `
	IsHidden      omit.Val[bool]       `db:"is_hidden" `
	ImgURL        omitnull.Val[string] `db:"img_url" `
	CreatedAt     omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt     omit.Val[time.Time]  `db:"updated_at" `
}

func (s IntellectualPropertySetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.IPRankGroupID.IsValue() {
		vals = append(vals, "ip_rank_group_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Stock.IsValue() {
		vals = append(vals, "stock")
	}
	if s.IsHidden.IsValue() {
		vals = append(vals, "is_hidden")
	}
	if !s.ImgURL.IsUnset() {
		vals = append(vals, "img_url")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s IntellectualPropertySetter) Overwrite(t *IntellectualProperty) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.IPRankGroupID.IsValue() {
		t.IPRankGroupID = s.IPRankGroupID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Stock.IsValue() {
		t.Stock = s.Stock.MustGet()
	}
	if s.IsHidden.IsValue() {
		t.IsHidden = s.IsHidden.MustGet()
	}
	if !s.ImgURL.IsUnset() {
		t.ImgURL = s.ImgURL.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *IntellectualPropertySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return IntellectualProperties.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IPRankGroupID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IPRankGroupID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Stock.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Stock.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IsHidden.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IsHidden.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.ImgURL.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ImgURL.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s IntellectualPropertySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("intellectual_properties")...)
}

func (s IntellectualPropertySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.IPRankGroupID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "ip_rank_group_id")...),
			mysql.Arg(s.IPRankGroupID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.Stock.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "stock")...),
			mysql.Arg(s.Stock),
		}})
	}

	if s.IsHidden.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "is_hidden")...),
			mysql.Arg(s.IsHidden),
		}})
	}

	if !s.ImgURL.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "img_url")...),
			mysql.Arg(s.ImgURL),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindIntellectualProperty retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindIntellectualProperty(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*IntellectualProperty, error) {
	if len(cols) == 0 {
		return IntellectualProperties.Query(
			sm.Where(IntellectualProperties.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return IntellectualProperties.Query(
		sm.Where(IntellectualProperties.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(IntellectualProperties.Columns.Only(cols...)),
	).One(ctx, exec)
}

// IntellectualPropertyExists checks the presence of a single record by primary key
func IntellectualPropertyExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return IntellectualProperties.Query(
		sm.Where(IntellectualProperties.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after IntellectualProperty is retrieved from the database
func (o *IntellectualProperty) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = IntellectualProperties.AfterSelectHooks.RunHooks(ctx, exec, IntellectualPropertySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = IntellectualProperties.AfterInsertHooks.RunHooks(ctx, exec, IntellectualPropertySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = IntellectualProperties.AfterUpdateHooks.RunHooks(ctx, exec, IntellectualPropertySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = IntellectualProperties.AfterDeleteHooks.RunHooks(ctx, exec, IntellectualPropertySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the IntellectualProperty
func (o *IntellectualProperty) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *IntellectualProperty) pkEQ() dialect.Expression {
	return mysql.Quote("intellectual_properties", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the IntellectualProperty
func (o *IntellectualProperty) Update(ctx context.Context, exec bob.Executor, s *IntellectualPropertySetter) error {
	_, err := IntellectualProperties.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single IntellectualProperty record with an executor
func (o *IntellectualProperty) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := IntellectualProperties.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the IntellectualProperty using the executor
func (o *IntellectualProperty) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := IntellectualProperties.Query(
		sm.Where(IntellectualProperties.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after IntellectualPropertySlice is retrieved from the database
func (o IntellectualPropertySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = IntellectualProperties.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = IntellectualProperties.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = IntellectualProperties.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = IntellectualProperties.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o IntellectualPropertySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("intellectual_properties", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o IntellectualPropertySlice) copyMatchingRows(from ...*IntellectualProperty) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o IntellectualPropertySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return IntellectualProperties.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *IntellectualProperty:
				o.copyMatchingRows(retrieved)
			case []*IntellectualProperty:
				o.copyMatchingRows(retrieved...)
			case IntellectualPropertySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a IntellectualProperty or a slice of IntellectualProperty
				// then run the AfterUpdateHooks on the slice
				_, err = IntellectualProperties.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o IntellectualPropertySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return IntellectualProperties.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *IntellectualProperty:
				o.copyMatchingRows(retrieved)
			case []*IntellectualProperty:
				o.copyMatchingRows(retrieved...)
			case IntellectualPropertySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a IntellectualProperty or a slice of IntellectualProperty
				// then run the AfterDeleteHooks on the slice
				_, err = IntellectualProperties.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o IntellectualPropertySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals IntellectualPropertySetter) error {
	_, err := IntellectualProperties.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o IntellectualPropertySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := IntellectualProperties.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o IntellectualPropertySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := IntellectualProperties.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// IPRankGroupIntellectualPropertyRankGroup starts a query for related objects on intellectual_property_rank_groups
func (o *IntellectualProperty) IPRankGroupIntellectualPropertyRankGroup(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertyRankGroupsQuery {
	return IntellectualPropertyRankGroups.Query(append(mods,
		sm.Where(IntellectualPropertyRankGroups.Columns.ID.EQ(mysql.Arg(o.IPRankGroupID))),
	)...)
}

func (os IntellectualPropertySlice) IPRankGroupIntellectualPropertyRankGroup(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertyRankGroupsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.IPRankGroupID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return IntellectualPropertyRankGroups.Query(append(mods,
		sm.Where(mysql.Group(IntellectualPropertyRankGroups.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// IDPurchaseHistories starts a query for related objects on purchase_histories
func (o *IntellectualProperty) IDPurchaseHistories(mods ...bob.Mod[*dialect.SelectQuery]) PurchaseHistoriesQuery {
	return PurchaseHistories.Query(append(mods,
		sm.Where(PurchaseHistories.Columns.IPID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os IntellectualPropertySlice) IDPurchaseHistories(mods ...bob.Mod[*dialect.SelectQuery]) PurchaseHistoriesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return PurchaseHistories.Query(append(mods,
		sm.Where(mysql.Group(PurchaseHistories.Columns.IPID).OP("IN", PKArgExpr)),
	)...)
}

func attachIntellectualPropertyIPRankGroupIntellectualPropertyRankGroup0(ctx context.Context, exec bob.Executor, count int, intellectualProperty0 *IntellectualProperty, intellectualPropertyRankGroup1 *IntellectualPropertyRankGroup) (*IntellectualProperty, error) {
	setter := &IntellectualPropertySetter{
		IPRankGroupID: omit.From(intellectualPropertyRankGroup1.ID),
	}

	err := intellectualProperty0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachIntellectualPropertyIPRankGroupIntellectualPropertyRankGroup0: %w", err)
	}

	return intellectualProperty0, nil
}

func (intellectualProperty0 *IntellectualProperty) InsertIPRankGroupIntellectualPropertyRankGroup(ctx context.Context, exec bob.Executor, related *IntellectualPropertyRankGroupSetter) error {
	var err error

	intellectualPropertyRankGroup1, err := IntellectualPropertyRankGroups.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachIntellectualPropertyIPRankGroupIntellectualPropertyRankGroup0(ctx, exec, 1, intellectualProperty0, intellectualPropertyRankGroup1)
	if err != nil {
		return err
	}

	intellectualProperty0.R.IPRankGroupIntellectualPropertyRankGroup = intellectualPropertyRankGroup1

	intellectualPropertyRankGroup1.R.IPRankGroupIntellectualProperties = append(intellectualPropertyRankGroup1.R.IPRankGroupIntellectualProperties, intellectualProperty0)

	return nil
}

func (intellectualProperty0 *IntellectualProperty) AttachIPRankGroupIntellectualPropertyRankGroup(ctx context.Context, exec bob.Executor, intellectualPropertyRankGroup1 *IntellectualPropertyRankGroup) error {
	var err error

	_, err = attachIntellectualPropertyIPRankGroupIntellectualPropertyRankGroup0(ctx, exec, 1, intellectualProperty0, intellectualPropertyRankGroup1)
	if err != nil {
		return err
	}

	intellectualProperty0.R.IPRankGroupIntellectualPropertyRankGroup = intellectualPropertyRankGroup1

	intellectualPropertyRankGroup1.R.IPRankGroupIntellectualProperties = append(intellectualPropertyRankGroup1.R.IPRankGroupIntellectualProperties, intellectualProperty0)

	return nil
}

func insertIntellectualPropertyIDPurchaseHistories0(ctx context.Context, exec bob.Executor, purchaseHistories1 []*PurchaseHistorySetter, intellectualProperty0 *IntellectualProperty) (PurchaseHistorySlice, error) {
	for i := range purchaseHistories1 {
		purchaseHistories1[i].IPID = omit.From(intellectualProperty0.ID)
	}

	ret, err := PurchaseHistories.Insert(bob.ToMods(purchaseHistories1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertIntellectualPropertyIDPurchaseHistories0: %w", err)
	}

	return ret, nil
}

func attachIntellectualPropertyIDPurchaseHistories0(ctx context.Context, exec bob.Executor, count int, purchaseHistories1 PurchaseHistorySlice, intellectualProperty0 *IntellectualProperty) (PurchaseHistorySlice, error) {
	setter := &PurchaseHistorySetter{
		IPID: omit.From(intellectualProperty0.ID),
	}

	err := purchaseHistories1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachIntellectualPropertyIDPurchaseHistories0: %w", err)
	}

	return purchaseHistories1, nil
}

func (intellectualProperty0 *IntellectualProperty) InsertIDPurchaseHistories(ctx context.Context, exec bob.Executor, related ...*PurchaseHistorySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	purchaseHistories1, err := insertIntellectualPropertyIDPurchaseHistories0(ctx, exec, related, intellectualProperty0)
	if err != nil {
		return err
	}

	intellectualProperty0.R.IDPurchaseHistories = append(intellectualProperty0.R.IDPurchaseHistories, purchaseHistories1...)

	for _, rel := range purchaseHistories1 {
		rel.R.IPIntellectualProperty = intellectualProperty0
	}
	return nil
}

func (intellectualProperty0 *IntellectualProperty) AttachIDPurchaseHistories(ctx context.Context, exec bob.Executor, related ...*PurchaseHistory) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	purchaseHistories1 := PurchaseHistorySlice(related)

	_, err = attachIntellectualPropertyIDPurchaseHistories0(ctx, exec, len(related), purchaseHistories1, intellectualProperty0)
	if err != nil {
		return err
	}

	intellectualProperty0.R.IDPurchaseHistories = append(intellectualProperty0.R.IDPurchaseHistories, purchaseHistories1...)

	for _, rel := range related {
		rel.R.IPIntellectualProperty = intellectualProperty0
	}

	return nil
}

type intellectualPropertyWhere[Q mysql.Filterable] struct {
	ID            mysql.WhereMod[Q, string]
	IPRankGroupID mysql.WhereMod[Q, string]
	Name          mysql.WhereMod[Q, string]
	Stock         mysql.WhereMod[Q, int32]
	IsHidden      mysql.WhereMod[Q, bool]
	ImgURL        mysql.WhereNullMod[Q, string]
	CreatedAt     mysql.WhereMod[Q, time.Time]
	UpdatedAt     mysql.WhereMod[Q, time.Time]
}

func (intellectualPropertyWhere[Q]) AliasedAs(alias string) intellectualPropertyWhere[Q] {
	return buildIntellectualPropertyWhere[Q](buildIntellectualPropertyColumns(alias))
}

func buildIntellectualPropertyWhere[Q mysql.Filterable](cols intellectualPropertyColumns) intellectualPropertyWhere[Q] {
	return intellectualPropertyWhere[Q]{
		ID:            mysql.Where[Q, string](cols.ID),
		IPRankGroupID: mysql.Where[Q, string](cols.IPRankGroupID),
		Name:          mysql.Where[Q, string](cols.Name),
		Stock:         mysql.Where[Q, int32](cols.Stock),
		IsHidden:      mysql.Where[Q, bool](cols.IsHidden),
		ImgURL:        mysql.WhereNull[Q, string](cols.ImgURL),
		CreatedAt:     mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:     mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *IntellectualProperty) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "IPRankGroupIntellectualPropertyRankGroup":
		rel, ok := retrieved.(*IntellectualPropertyRankGroup)
		if !ok {
			return fmt.Errorf("intellectualProperty cannot load %T as %q", retrieved, name)
		}

		o.R.IPRankGroupIntellectualPropertyRankGroup = rel

		if rel != nil {
			rel.R.IPRankGroupIntellectualProperties = IntellectualPropertySlice{o}
		}
		return nil
	case "IDPurchaseHistories":
		rels, ok := retrieved.(PurchaseHistorySlice)
		if !ok {
			return fmt.Errorf("intellectualProperty cannot load %T as %q", retrieved, name)
		}

		o.R.IDPurchaseHistories = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.IPIntellectualProperty = o
			}
		}
		return nil
	default:
		return fmt.Errorf("intellectualProperty has no relationship %q", name)
	}
}

type intellectualPropertyPreloader struct {
	IPRankGroupIntellectualPropertyRankGroup func(...mysql.PreloadOption) mysql.Preloader
}

func buildIntellectualPropertyPreloader() intellectualPropertyPreloader {
	return intellectualPropertyPreloader{
		IPRankGroupIntellectualPropertyRankGroup: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*IntellectualPropertyRankGroup, IntellectualPropertyRankGroupSlice](mysql.PreloadRel{
				Name: "IPRankGroupIntellectualPropertyRankGroup",
				Sides: []mysql.PreloadSide{
					{
						From:        IntellectualProperties,
						To:          IntellectualPropertyRankGroups,
						FromColumns: []string{"ip_rank_group_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, IntellectualPropertyRankGroups.Columns.Names(), opts...)
		},
	}
}

type intellectualPropertyThenLoader[Q orm.Loadable] struct {
	IPRankGroupIntellectualPropertyRankGroup func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	IDPurchaseHistories                      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildIntellectualPropertyThenLoader[Q orm.Loadable]() intellectualPropertyThenLoader[Q] {
	type IPRankGroupIntellectualPropertyRankGroupLoadInterface interface {
		LoadIPRankGroupIntellectualPropertyRankGroup(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type IDPurchaseHistoriesLoadInterface interface {
		LoadIDPurchaseHistories(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return intellectualPropertyThenLoader[Q]{
		IPRankGroupIntellectualPropertyRankGroup: thenLoadBuilder[Q](
			"IPRankGroupIntellectualPropertyRankGroup",
			func(ctx context.Context, exec bob.Executor, retrieved IPRankGroupIntellectualPropertyRankGroupLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadIPRankGroupIntellectualPropertyRankGroup(ctx, exec, mods...)
			},
		),
		IDPurchaseHistories: thenLoadBuilder[Q](
			"IDPurchaseHistories",
			func(ctx context.Context, exec bob.Executor, retrieved IDPurchaseHistoriesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadIDPurchaseHistories(ctx, exec, mods...)
			},
		),
	}
}

// LoadIPRankGroupIntellectualPropertyRankGroup loads the intellectualProperty's IPRankGroupIntellectualPropertyRankGroup into the .R struct
func (o *IntellectualProperty) LoadIPRankGroupIntellectualPropertyRankGroup(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IPRankGroupIntellectualPropertyRankGroup = nil

	related, err := o.IPRankGroupIntellectualPropertyRankGroup(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.IPRankGroupIntellectualProperties = IntellectualPropertySlice{o}

	o.R.IPRankGroupIntellectualPropertyRankGroup = related
	return nil
}

// LoadIPRankGroupIntellectualPropertyRankGroup loads the intellectualProperty's IPRankGroupIntellectualPropertyRankGroup into the .R struct
func (os IntellectualPropertySlice) LoadIPRankGroupIntellectualPropertyRankGroup(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	intellectualPropertyRankGroups, err := os.IPRankGroupIntellectualPropertyRankGroup(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range intellectualPropertyRankGroups {

			if !(o.IPRankGroupID == rel.ID) {
				continue
			}

			rel.R.IPRankGroupIntellectualProperties = append(rel.R.IPRankGroupIntellectualProperties, o)

			o.R.IPRankGroupIntellectualPropertyRankGroup = rel
			break
		}
	}

	return nil
}

// LoadIDPurchaseHistories loads the intellectualProperty's IDPurchaseHistories into the .R struct
func (o *IntellectualProperty) LoadIDPurchaseHistories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IDPurchaseHistories = nil

	related, err := o.IDPurchaseHistories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.IPIntellectualProperty = o
	}

	o.R.IDPurchaseHistories = related
	return nil
}

// LoadIDPurchaseHistories loads the intellectualProperty's IDPurchaseHistories into the .R struct
func (os IntellectualPropertySlice) LoadIDPurchaseHistories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	purchaseHistories, err := os.IDPurchaseHistories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.IDPurchaseHistories = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range purchaseHistories {

			if !(o.ID == rel.IPID) {
				continue
			}

			rel.R.IPIntellectualProperty = o

			o.R.IDPurchaseHistories = append(o.R.IDPurchaseHistories, rel)
		}
	}

	return nil
}

type intellectualPropertyJoins[Q dialect.Joinable] struct {
	typ                                      string
	IPRankGroupIntellectualPropertyRankGroup modAs[Q, intellectualPropertyRankGroupColumns]
	IDPurchaseHistories                      modAs[Q, purchaseHistoryColumns]
}

func (j intellectualPropertyJoins[Q]) aliasedAs(alias string) intellectualPropertyJoins[Q] {
	return buildIntellectualPropertyJoins[Q](buildIntellectualPropertyColumns(alias), j.typ)
}

func buildIntellectualPropertyJoins[Q dialect.Joinable](cols intellectualPropertyColumns, typ string) intellectualPropertyJoins[Q] {
	return intellectualPropertyJoins[Q]{
		typ: typ,
		IPRankGroupIntellectualPropertyRankGroup: modAs[Q, intellectualPropertyRankGroupColumns]{
			c: IntellectualPropertyRankGroups.Columns,
			f: func(to intellectualPropertyRankGroupColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, IntellectualPropertyRankGroups.Name().As(to.Alias())).On(
						to.ID.EQ(cols.IPRankGroupID),
					))
				}

				return mods
			},
		},
		IDPurchaseHistories: modAs[Q, purchaseHistoryColumns]{
			c: PurchaseHistories.Columns,
			f: func(to purchaseHistoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PurchaseHistories.Name().As(to.Alias())).On(
						to.IPID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
