// Code generated by BobGen mysql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	enums "kujicole/infra/bob/enums"
)

// IntellectualPropertyRankGroup is an object representing the database table.
type IntellectualPropertyRankGroup struct {
	ID           string                                   `db:"id,pk" `
	IPCategoryID string                                   `db:"ip_category_id" `
	Name         string                                   `db:"name" `
	Rank         enums.IntellectualPropertyRankGroupsRank `db:"rank" `
	EmissionRate int32                                    `db:"emission_rate" `
	Explanation  null.Val[string]                         `db:"explanation" `
	IsHidden     bool                                     `db:"is_hidden" `
	Comments     null.Val[string]                         `db:"comments" `
	ImgURL       null.Val[string]                         `db:"img_url" `
	CreatedAt    time.Time                                `db:"created_at" `
	UpdatedAt    time.Time                                `db:"updated_at" `

	R intellectualPropertyRankGroupR `db:"-" `
}

// IntellectualPropertyRankGroupSlice is an alias for a slice of pointers to IntellectualPropertyRankGroup.
// This should almost always be used instead of []*IntellectualPropertyRankGroup.
type IntellectualPropertyRankGroupSlice []*IntellectualPropertyRankGroup

// IntellectualPropertyRankGroups contains methods to work with the intellectual_property_rank_groups table
var IntellectualPropertyRankGroups = mysql.NewTablex[*IntellectualPropertyRankGroup, IntellectualPropertyRankGroupSlice, *IntellectualPropertyRankGroupSetter]("intellectual_property_rank_groups", buildIntellectualPropertyRankGroupColumns("intellectual_property_rank_groups"), []string{"id"})

// IntellectualPropertyRankGroupsQuery is a query on the intellectual_property_rank_groups table
type IntellectualPropertyRankGroupsQuery = *mysql.ViewQuery[*IntellectualPropertyRankGroup, IntellectualPropertyRankGroupSlice]

// intellectualPropertyRankGroupR is where relationships are stored.
type intellectualPropertyRankGroupR struct {
	IPRankGroupIntellectualProperties      IntellectualPropertySlice     // intellectual_properties_ibfk_1
	IPCategoryIntellectualPropertyCategory *IntellectualPropertyCategory // intellectual_property_rank_groups_ibfk_1
}

func buildIntellectualPropertyRankGroupColumns(alias string) intellectualPropertyRankGroupColumns {
	return intellectualPropertyRankGroupColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "ip_category_id", "name", "rank", "emission_rate", "explanation", "is_hidden", "comments", "img_url", "created_at", "updated_at",
		).WithParent("intellectual_property_rank_groups"),
		tableAlias:   alias,
		ID:           mysql.Quote(alias, "id"),
		IPCategoryID: mysql.Quote(alias, "ip_category_id"),
		Name:         mysql.Quote(alias, "name"),
		Rank:         mysql.Quote(alias, "rank"),
		EmissionRate: mysql.Quote(alias, "emission_rate"),
		Explanation:  mysql.Quote(alias, "explanation"),
		IsHidden:     mysql.Quote(alias, "is_hidden"),
		Comments:     mysql.Quote(alias, "comments"),
		ImgURL:       mysql.Quote(alias, "img_url"),
		CreatedAt:    mysql.Quote(alias, "created_at"),
		UpdatedAt:    mysql.Quote(alias, "updated_at"),
	}
}

type intellectualPropertyRankGroupColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           mysql.Expression
	IPCategoryID mysql.Expression
	Name         mysql.Expression
	Rank         mysql.Expression
	EmissionRate mysql.Expression
	Explanation  mysql.Expression
	IsHidden     mysql.Expression
	Comments     mysql.Expression
	ImgURL       mysql.Expression
	CreatedAt    mysql.Expression
	UpdatedAt    mysql.Expression
}

func (c intellectualPropertyRankGroupColumns) Alias() string {
	return c.tableAlias
}

func (intellectualPropertyRankGroupColumns) AliasedAs(alias string) intellectualPropertyRankGroupColumns {
	return buildIntellectualPropertyRankGroupColumns(alias)
}

// IntellectualPropertyRankGroupSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type IntellectualPropertyRankGroupSetter struct {
	ID           omit.Val[string]                                   `db:"id,pk" `
	IPCategoryID omit.Val[string]                                   `db:"ip_category_id" `
	Name         omit.Val[string]                                   `db:"name" `
	Rank         omit.Val[enums.IntellectualPropertyRankGroupsRank] `db:"rank" `
	EmissionRate omit.Val[int32]                                    `db:"emission_rate" `
	Explanation  omitnull.Val[string]                               `db:"explanation" `
	IsHidden     omit.Val[bool]                                     `db:"is_hidden" `
	Comments     omitnull.Val[string]                               `db:"comments" `
	ImgURL       omitnull.Val[string]                               `db:"img_url" `
	CreatedAt    omit.Val[time.Time]                                `db:"created_at" `
	UpdatedAt    omit.Val[time.Time]                                `db:"updated_at" `
}

func (s IntellectualPropertyRankGroupSetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.IPCategoryID.IsValue() {
		vals = append(vals, "ip_category_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Rank.IsValue() {
		vals = append(vals, "rank")
	}
	if s.EmissionRate.IsValue() {
		vals = append(vals, "emission_rate")
	}
	if !s.Explanation.IsUnset() {
		vals = append(vals, "explanation")
	}
	if s.IsHidden.IsValue() {
		vals = append(vals, "is_hidden")
	}
	if !s.Comments.IsUnset() {
		vals = append(vals, "comments")
	}
	if !s.ImgURL.IsUnset() {
		vals = append(vals, "img_url")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s IntellectualPropertyRankGroupSetter) Overwrite(t *IntellectualPropertyRankGroup) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.IPCategoryID.IsValue() {
		t.IPCategoryID = s.IPCategoryID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Rank.IsValue() {
		t.Rank = s.Rank.MustGet()
	}
	if s.EmissionRate.IsValue() {
		t.EmissionRate = s.EmissionRate.MustGet()
	}
	if !s.Explanation.IsUnset() {
		t.Explanation = s.Explanation.MustGetNull()
	}
	if s.IsHidden.IsValue() {
		t.IsHidden = s.IsHidden.MustGet()
	}
	if !s.Comments.IsUnset() {
		t.Comments = s.Comments.MustGetNull()
	}
	if !s.ImgURL.IsUnset() {
		t.ImgURL = s.ImgURL.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *IntellectualPropertyRankGroupSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return IntellectualPropertyRankGroups.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IPCategoryID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IPCategoryID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Rank.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Rank.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.EmissionRate.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.EmissionRate.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.Explanation.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Explanation.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IsHidden.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IsHidden.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.Comments.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Comments.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.ImgURL.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ImgURL.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s IntellectualPropertyRankGroupSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("intellectual_property_rank_groups")...)
}

func (s IntellectualPropertyRankGroupSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.IPCategoryID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "ip_category_id")...),
			mysql.Arg(s.IPCategoryID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.Rank.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "rank")...),
			mysql.Arg(s.Rank),
		}})
	}

	if s.EmissionRate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "emission_rate")...),
			mysql.Arg(s.EmissionRate),
		}})
	}

	if !s.Explanation.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "explanation")...),
			mysql.Arg(s.Explanation),
		}})
	}

	if s.IsHidden.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "is_hidden")...),
			mysql.Arg(s.IsHidden),
		}})
	}

	if !s.Comments.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "comments")...),
			mysql.Arg(s.Comments),
		}})
	}

	if !s.ImgURL.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "img_url")...),
			mysql.Arg(s.ImgURL),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindIntellectualPropertyRankGroup retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindIntellectualPropertyRankGroup(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*IntellectualPropertyRankGroup, error) {
	if len(cols) == 0 {
		return IntellectualPropertyRankGroups.Query(
			sm.Where(IntellectualPropertyRankGroups.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return IntellectualPropertyRankGroups.Query(
		sm.Where(IntellectualPropertyRankGroups.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(IntellectualPropertyRankGroups.Columns.Only(cols...)),
	).One(ctx, exec)
}

// IntellectualPropertyRankGroupExists checks the presence of a single record by primary key
func IntellectualPropertyRankGroupExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return IntellectualPropertyRankGroups.Query(
		sm.Where(IntellectualPropertyRankGroups.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after IntellectualPropertyRankGroup is retrieved from the database
func (o *IntellectualPropertyRankGroup) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = IntellectualPropertyRankGroups.AfterSelectHooks.RunHooks(ctx, exec, IntellectualPropertyRankGroupSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = IntellectualPropertyRankGroups.AfterInsertHooks.RunHooks(ctx, exec, IntellectualPropertyRankGroupSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = IntellectualPropertyRankGroups.AfterUpdateHooks.RunHooks(ctx, exec, IntellectualPropertyRankGroupSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = IntellectualPropertyRankGroups.AfterDeleteHooks.RunHooks(ctx, exec, IntellectualPropertyRankGroupSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the IntellectualPropertyRankGroup
func (o *IntellectualPropertyRankGroup) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *IntellectualPropertyRankGroup) pkEQ() dialect.Expression {
	return mysql.Quote("intellectual_property_rank_groups", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the IntellectualPropertyRankGroup
func (o *IntellectualPropertyRankGroup) Update(ctx context.Context, exec bob.Executor, s *IntellectualPropertyRankGroupSetter) error {
	_, err := IntellectualPropertyRankGroups.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single IntellectualPropertyRankGroup record with an executor
func (o *IntellectualPropertyRankGroup) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := IntellectualPropertyRankGroups.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the IntellectualPropertyRankGroup using the executor
func (o *IntellectualPropertyRankGroup) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := IntellectualPropertyRankGroups.Query(
		sm.Where(IntellectualPropertyRankGroups.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after IntellectualPropertyRankGroupSlice is retrieved from the database
func (o IntellectualPropertyRankGroupSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = IntellectualPropertyRankGroups.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = IntellectualPropertyRankGroups.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = IntellectualPropertyRankGroups.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = IntellectualPropertyRankGroups.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o IntellectualPropertyRankGroupSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("intellectual_property_rank_groups", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o IntellectualPropertyRankGroupSlice) copyMatchingRows(from ...*IntellectualPropertyRankGroup) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o IntellectualPropertyRankGroupSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return IntellectualPropertyRankGroups.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *IntellectualPropertyRankGroup:
				o.copyMatchingRows(retrieved)
			case []*IntellectualPropertyRankGroup:
				o.copyMatchingRows(retrieved...)
			case IntellectualPropertyRankGroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a IntellectualPropertyRankGroup or a slice of IntellectualPropertyRankGroup
				// then run the AfterUpdateHooks on the slice
				_, err = IntellectualPropertyRankGroups.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o IntellectualPropertyRankGroupSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return IntellectualPropertyRankGroups.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *IntellectualPropertyRankGroup:
				o.copyMatchingRows(retrieved)
			case []*IntellectualPropertyRankGroup:
				o.copyMatchingRows(retrieved...)
			case IntellectualPropertyRankGroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a IntellectualPropertyRankGroup or a slice of IntellectualPropertyRankGroup
				// then run the AfterDeleteHooks on the slice
				_, err = IntellectualPropertyRankGroups.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o IntellectualPropertyRankGroupSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals IntellectualPropertyRankGroupSetter) error {
	_, err := IntellectualPropertyRankGroups.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o IntellectualPropertyRankGroupSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := IntellectualPropertyRankGroups.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o IntellectualPropertyRankGroupSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := IntellectualPropertyRankGroups.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// IPRankGroupIntellectualProperties starts a query for related objects on intellectual_properties
func (o *IntellectualPropertyRankGroup) IPRankGroupIntellectualProperties(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertiesQuery {
	return IntellectualProperties.Query(append(mods,
		sm.Where(IntellectualProperties.Columns.IPRankGroupID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os IntellectualPropertyRankGroupSlice) IPRankGroupIntellectualProperties(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertiesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return IntellectualProperties.Query(append(mods,
		sm.Where(mysql.Group(IntellectualProperties.Columns.IPRankGroupID).OP("IN", PKArgExpr)),
	)...)
}

// IPCategoryIntellectualPropertyCategory starts a query for related objects on intellectual_property_categories
func (o *IntellectualPropertyRankGroup) IPCategoryIntellectualPropertyCategory(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertyCategoriesQuery {
	return IntellectualPropertyCategories.Query(append(mods,
		sm.Where(IntellectualPropertyCategories.Columns.ID.EQ(mysql.Arg(o.IPCategoryID))),
	)...)
}

func (os IntellectualPropertyRankGroupSlice) IPCategoryIntellectualPropertyCategory(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertyCategoriesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.IPCategoryID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return IntellectualPropertyCategories.Query(append(mods,
		sm.Where(mysql.Group(IntellectualPropertyCategories.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertIntellectualPropertyRankGroupIPRankGroupIntellectualProperties0(ctx context.Context, exec bob.Executor, intellectualProperties1 []*IntellectualPropertySetter, intellectualPropertyRankGroup0 *IntellectualPropertyRankGroup) (IntellectualPropertySlice, error) {
	for i := range intellectualProperties1 {
		intellectualProperties1[i].IPRankGroupID = omit.From(intellectualPropertyRankGroup0.ID)
	}

	ret, err := IntellectualProperties.Insert(bob.ToMods(intellectualProperties1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertIntellectualPropertyRankGroupIPRankGroupIntellectualProperties0: %w", err)
	}

	return ret, nil
}

func attachIntellectualPropertyRankGroupIPRankGroupIntellectualProperties0(ctx context.Context, exec bob.Executor, count int, intellectualProperties1 IntellectualPropertySlice, intellectualPropertyRankGroup0 *IntellectualPropertyRankGroup) (IntellectualPropertySlice, error) {
	setter := &IntellectualPropertySetter{
		IPRankGroupID: omit.From(intellectualPropertyRankGroup0.ID),
	}

	err := intellectualProperties1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachIntellectualPropertyRankGroupIPRankGroupIntellectualProperties0: %w", err)
	}

	return intellectualProperties1, nil
}

func (intellectualPropertyRankGroup0 *IntellectualPropertyRankGroup) InsertIPRankGroupIntellectualProperties(ctx context.Context, exec bob.Executor, related ...*IntellectualPropertySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	intellectualProperties1, err := insertIntellectualPropertyRankGroupIPRankGroupIntellectualProperties0(ctx, exec, related, intellectualPropertyRankGroup0)
	if err != nil {
		return err
	}

	intellectualPropertyRankGroup0.R.IPRankGroupIntellectualProperties = append(intellectualPropertyRankGroup0.R.IPRankGroupIntellectualProperties, intellectualProperties1...)

	for _, rel := range intellectualProperties1 {
		rel.R.IPRankGroupIntellectualPropertyRankGroup = intellectualPropertyRankGroup0
	}
	return nil
}

func (intellectualPropertyRankGroup0 *IntellectualPropertyRankGroup) AttachIPRankGroupIntellectualProperties(ctx context.Context, exec bob.Executor, related ...*IntellectualProperty) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	intellectualProperties1 := IntellectualPropertySlice(related)

	_, err = attachIntellectualPropertyRankGroupIPRankGroupIntellectualProperties0(ctx, exec, len(related), intellectualProperties1, intellectualPropertyRankGroup0)
	if err != nil {
		return err
	}

	intellectualPropertyRankGroup0.R.IPRankGroupIntellectualProperties = append(intellectualPropertyRankGroup0.R.IPRankGroupIntellectualProperties, intellectualProperties1...)

	for _, rel := range related {
		rel.R.IPRankGroupIntellectualPropertyRankGroup = intellectualPropertyRankGroup0
	}

	return nil
}

func attachIntellectualPropertyRankGroupIPCategoryIntellectualPropertyCategory0(ctx context.Context, exec bob.Executor, count int, intellectualPropertyRankGroup0 *IntellectualPropertyRankGroup, intellectualPropertyCategory1 *IntellectualPropertyCategory) (*IntellectualPropertyRankGroup, error) {
	setter := &IntellectualPropertyRankGroupSetter{
		IPCategoryID: omit.From(intellectualPropertyCategory1.ID),
	}

	err := intellectualPropertyRankGroup0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachIntellectualPropertyRankGroupIPCategoryIntellectualPropertyCategory0: %w", err)
	}

	return intellectualPropertyRankGroup0, nil
}

func (intellectualPropertyRankGroup0 *IntellectualPropertyRankGroup) InsertIPCategoryIntellectualPropertyCategory(ctx context.Context, exec bob.Executor, related *IntellectualPropertyCategorySetter) error {
	intellectualPropertyCategory1, err := IntellectualPropertyCategories.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachIntellectualPropertyRankGroupIPCategoryIntellectualPropertyCategory0(ctx, exec, 1, intellectualPropertyRankGroup0, intellectualPropertyCategory1)
	if err != nil {
		return err
	}

	intellectualPropertyRankGroup0.R.IPCategoryIntellectualPropertyCategory = intellectualPropertyCategory1

	intellectualPropertyCategory1.R.IPCategoryIntellectualPropertyRankGroups = append(intellectualPropertyCategory1.R.IPCategoryIntellectualPropertyRankGroups, intellectualPropertyRankGroup0)

	return nil
}

func (intellectualPropertyRankGroup0 *IntellectualPropertyRankGroup) AttachIPCategoryIntellectualPropertyCategory(ctx context.Context, exec bob.Executor, intellectualPropertyCategory1 *IntellectualPropertyCategory) error {
	var err error

	_, err = attachIntellectualPropertyRankGroupIPCategoryIntellectualPropertyCategory0(ctx, exec, 1, intellectualPropertyRankGroup0, intellectualPropertyCategory1)
	if err != nil {
		return err
	}

	intellectualPropertyRankGroup0.R.IPCategoryIntellectualPropertyCategory = intellectualPropertyCategory1

	intellectualPropertyCategory1.R.IPCategoryIntellectualPropertyRankGroups = append(intellectualPropertyCategory1.R.IPCategoryIntellectualPropertyRankGroups, intellectualPropertyRankGroup0)

	return nil
}

type intellectualPropertyRankGroupWhere[Q mysql.Filterable] struct {
	ID           mysql.WhereMod[Q, string]
	IPCategoryID mysql.WhereMod[Q, string]
	Name         mysql.WhereMod[Q, string]
	Rank         mysql.WhereMod[Q, enums.IntellectualPropertyRankGroupsRank]
	EmissionRate mysql.WhereMod[Q, int32]
	Explanation  mysql.WhereNullMod[Q, string]
	IsHidden     mysql.WhereMod[Q, bool]
	Comments     mysql.WhereNullMod[Q, string]
	ImgURL       mysql.WhereNullMod[Q, string]
	CreatedAt    mysql.WhereMod[Q, time.Time]
	UpdatedAt    mysql.WhereMod[Q, time.Time]
}

func (intellectualPropertyRankGroupWhere[Q]) AliasedAs(alias string) intellectualPropertyRankGroupWhere[Q] {
	return buildIntellectualPropertyRankGroupWhere[Q](buildIntellectualPropertyRankGroupColumns(alias))
}

func buildIntellectualPropertyRankGroupWhere[Q mysql.Filterable](cols intellectualPropertyRankGroupColumns) intellectualPropertyRankGroupWhere[Q] {
	return intellectualPropertyRankGroupWhere[Q]{
		ID:           mysql.Where[Q, string](cols.ID),
		IPCategoryID: mysql.Where[Q, string](cols.IPCategoryID),
		Name:         mysql.Where[Q, string](cols.Name),
		Rank:         mysql.Where[Q, enums.IntellectualPropertyRankGroupsRank](cols.Rank),
		EmissionRate: mysql.Where[Q, int32](cols.EmissionRate),
		Explanation:  mysql.WhereNull[Q, string](cols.Explanation),
		IsHidden:     mysql.Where[Q, bool](cols.IsHidden),
		Comments:     mysql.WhereNull[Q, string](cols.Comments),
		ImgURL:       mysql.WhereNull[Q, string](cols.ImgURL),
		CreatedAt:    mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *IntellectualPropertyRankGroup) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "IPRankGroupIntellectualProperties":
		rels, ok := retrieved.(IntellectualPropertySlice)
		if !ok {
			return fmt.Errorf("intellectualPropertyRankGroup cannot load %T as %q", retrieved, name)
		}

		o.R.IPRankGroupIntellectualProperties = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.IPRankGroupIntellectualPropertyRankGroup = o
			}
		}
		return nil
	case "IPCategoryIntellectualPropertyCategory":
		rel, ok := retrieved.(*IntellectualPropertyCategory)
		if !ok {
			return fmt.Errorf("intellectualPropertyRankGroup cannot load %T as %q", retrieved, name)
		}

		o.R.IPCategoryIntellectualPropertyCategory = rel

		if rel != nil {
			rel.R.IPCategoryIntellectualPropertyRankGroups = IntellectualPropertyRankGroupSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("intellectualPropertyRankGroup has no relationship %q", name)
	}
}

type intellectualPropertyRankGroupPreloader struct {
	IPCategoryIntellectualPropertyCategory func(...mysql.PreloadOption) mysql.Preloader
}

func buildIntellectualPropertyRankGroupPreloader() intellectualPropertyRankGroupPreloader {
	return intellectualPropertyRankGroupPreloader{
		IPCategoryIntellectualPropertyCategory: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*IntellectualPropertyCategory, IntellectualPropertyCategorySlice](mysql.PreloadRel{
				Name: "IPCategoryIntellectualPropertyCategory",
				Sides: []mysql.PreloadSide{
					{
						From:        IntellectualPropertyRankGroups,
						To:          IntellectualPropertyCategories,
						FromColumns: []string{"ip_category_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, IntellectualPropertyCategories.Columns.Names(), opts...)
		},
	}
}

type intellectualPropertyRankGroupThenLoader[Q orm.Loadable] struct {
	IPRankGroupIntellectualProperties      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	IPCategoryIntellectualPropertyCategory func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildIntellectualPropertyRankGroupThenLoader[Q orm.Loadable]() intellectualPropertyRankGroupThenLoader[Q] {
	type IPRankGroupIntellectualPropertiesLoadInterface interface {
		LoadIPRankGroupIntellectualProperties(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type IPCategoryIntellectualPropertyCategoryLoadInterface interface {
		LoadIPCategoryIntellectualPropertyCategory(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return intellectualPropertyRankGroupThenLoader[Q]{
		IPRankGroupIntellectualProperties: thenLoadBuilder[Q](
			"IPRankGroupIntellectualProperties",
			func(ctx context.Context, exec bob.Executor, retrieved IPRankGroupIntellectualPropertiesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadIPRankGroupIntellectualProperties(ctx, exec, mods...)
			},
		),
		IPCategoryIntellectualPropertyCategory: thenLoadBuilder[Q](
			"IPCategoryIntellectualPropertyCategory",
			func(ctx context.Context, exec bob.Executor, retrieved IPCategoryIntellectualPropertyCategoryLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadIPCategoryIntellectualPropertyCategory(ctx, exec, mods...)
			},
		),
	}
}

// LoadIPRankGroupIntellectualProperties loads the intellectualPropertyRankGroup's IPRankGroupIntellectualProperties into the .R struct
func (o *IntellectualPropertyRankGroup) LoadIPRankGroupIntellectualProperties(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IPRankGroupIntellectualProperties = nil

	related, err := o.IPRankGroupIntellectualProperties(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.IPRankGroupIntellectualPropertyRankGroup = o
	}

	o.R.IPRankGroupIntellectualProperties = related
	return nil
}

// LoadIPRankGroupIntellectualProperties loads the intellectualPropertyRankGroup's IPRankGroupIntellectualProperties into the .R struct
func (os IntellectualPropertyRankGroupSlice) LoadIPRankGroupIntellectualProperties(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	intellectualProperties, err := os.IPRankGroupIntellectualProperties(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.IPRankGroupIntellectualProperties = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range intellectualProperties {

			if !(o.ID == rel.IPRankGroupID) {
				continue
			}

			rel.R.IPRankGroupIntellectualPropertyRankGroup = o

			o.R.IPRankGroupIntellectualProperties = append(o.R.IPRankGroupIntellectualProperties, rel)
		}
	}

	return nil
}

// LoadIPCategoryIntellectualPropertyCategory loads the intellectualPropertyRankGroup's IPCategoryIntellectualPropertyCategory into the .R struct
func (o *IntellectualPropertyRankGroup) LoadIPCategoryIntellectualPropertyCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IPCategoryIntellectualPropertyCategory = nil

	related, err := o.IPCategoryIntellectualPropertyCategory(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.IPCategoryIntellectualPropertyRankGroups = IntellectualPropertyRankGroupSlice{o}

	o.R.IPCategoryIntellectualPropertyCategory = related
	return nil
}

// LoadIPCategoryIntellectualPropertyCategory loads the intellectualPropertyRankGroup's IPCategoryIntellectualPropertyCategory into the .R struct
func (os IntellectualPropertyRankGroupSlice) LoadIPCategoryIntellectualPropertyCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	intellectualPropertyCategories, err := os.IPCategoryIntellectualPropertyCategory(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range intellectualPropertyCategories {

			if !(o.IPCategoryID == rel.ID) {
				continue
			}

			rel.R.IPCategoryIntellectualPropertyRankGroups = append(rel.R.IPCategoryIntellectualPropertyRankGroups, o)

			o.R.IPCategoryIntellectualPropertyCategory = rel
			break
		}
	}

	return nil
}

type intellectualPropertyRankGroupJoins[Q dialect.Joinable] struct {
	typ                                    string
	IPRankGroupIntellectualProperties      modAs[Q, intellectualPropertyColumns]
	IPCategoryIntellectualPropertyCategory modAs[Q, intellectualPropertyCategoryColumns]
}

func (j intellectualPropertyRankGroupJoins[Q]) aliasedAs(alias string) intellectualPropertyRankGroupJoins[Q] {
	return buildIntellectualPropertyRankGroupJoins[Q](buildIntellectualPropertyRankGroupColumns(alias), j.typ)
}

func buildIntellectualPropertyRankGroupJoins[Q dialect.Joinable](cols intellectualPropertyRankGroupColumns, typ string) intellectualPropertyRankGroupJoins[Q] {
	return intellectualPropertyRankGroupJoins[Q]{
		typ: typ,
		IPRankGroupIntellectualProperties: modAs[Q, intellectualPropertyColumns]{
			c: IntellectualProperties.Columns,
			f: func(to intellectualPropertyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, IntellectualProperties.Name().As(to.Alias())).On(
						to.IPRankGroupID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		IPCategoryIntellectualPropertyCategory: modAs[Q, intellectualPropertyCategoryColumns]{
			c: IntellectualPropertyCategories.Columns,
			f: func(to intellectualPropertyCategoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, IntellectualPropertyCategories.Name().As(to.Alias())).On(
						to.ID.EQ(cols.IPCategoryID),
					))
				}

				return mods
			},
		},
	}
}
