// Code generated by BobGen mysql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// PurchaseHistory is an object representing the database table.
type PurchaseHistory struct {
	ID                     string    `db:"id,pk" `
	PurchaseTransactionID  string    `db:"purchase_transaction_id" `
	IntellectualPropertyID string    `db:"intellectual_property_id" `
	CreatedAt              time.Time `db:"created_at" `
	UpdatedAt              time.Time `db:"updated_at" `

	R purchaseHistoryR `db:"-" `
}

// PurchaseHistorySlice is an alias for a slice of pointers to PurchaseHistory.
// This should almost always be used instead of []*PurchaseHistory.
type PurchaseHistorySlice []*PurchaseHistory

// PurchaseHistories contains methods to work with the purchase_histories table
var PurchaseHistories = mysql.NewTablex[*PurchaseHistory, PurchaseHistorySlice, *PurchaseHistorySetter]("purchase_histories", buildPurchaseHistoryColumns("purchase_histories"), []string{"id"})

// PurchaseHistoriesQuery is a query on the purchase_histories table
type PurchaseHistoriesQuery = *mysql.ViewQuery[*PurchaseHistory, PurchaseHistorySlice]

// purchaseHistoryR is where relationships are stored.
type purchaseHistoryR struct {
	PurchaseTransaction  *PurchaseTransaction  // purchase_histories_ibfk_1
	IntellectualProperty *IntellectualProperty // purchase_histories_ibfk_2
}

func buildPurchaseHistoryColumns(alias string) purchaseHistoryColumns {
	return purchaseHistoryColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "purchase_transaction_id", "intellectual_property_id", "created_at", "updated_at",
		).WithParent("purchase_histories"),
		tableAlias:             alias,
		ID:                     mysql.Quote(alias, "id"),
		PurchaseTransactionID:  mysql.Quote(alias, "purchase_transaction_id"),
		IntellectualPropertyID: mysql.Quote(alias, "intellectual_property_id"),
		CreatedAt:              mysql.Quote(alias, "created_at"),
		UpdatedAt:              mysql.Quote(alias, "updated_at"),
	}
}

type purchaseHistoryColumns struct {
	expr.ColumnsExpr
	tableAlias             string
	ID                     mysql.Expression
	PurchaseTransactionID  mysql.Expression
	IntellectualPropertyID mysql.Expression
	CreatedAt              mysql.Expression
	UpdatedAt              mysql.Expression
}

func (c purchaseHistoryColumns) Alias() string {
	return c.tableAlias
}

func (purchaseHistoryColumns) AliasedAs(alias string) purchaseHistoryColumns {
	return buildPurchaseHistoryColumns(alias)
}

// PurchaseHistorySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PurchaseHistorySetter struct {
	ID                     omit.Val[string]    `db:"id,pk" `
	PurchaseTransactionID  omit.Val[string]    `db:"purchase_transaction_id" `
	IntellectualPropertyID omit.Val[string]    `db:"intellectual_property_id" `
	CreatedAt              omit.Val[time.Time] `db:"created_at" `
	UpdatedAt              omit.Val[time.Time] `db:"updated_at" `
}

func (s PurchaseHistorySetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.PurchaseTransactionID.IsValue() {
		vals = append(vals, "purchase_transaction_id")
	}
	if s.IntellectualPropertyID.IsValue() {
		vals = append(vals, "intellectual_property_id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s PurchaseHistorySetter) Overwrite(t *PurchaseHistory) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.PurchaseTransactionID.IsValue() {
		t.PurchaseTransactionID = s.PurchaseTransactionID.MustGet()
	}
	if s.IntellectualPropertyID.IsValue() {
		t.IntellectualPropertyID = s.IntellectualPropertyID.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *PurchaseHistorySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PurchaseHistories.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.PurchaseTransactionID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PurchaseTransactionID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IntellectualPropertyID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IntellectualPropertyID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s PurchaseHistorySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("purchase_histories")...)
}

func (s PurchaseHistorySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.PurchaseTransactionID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "purchase_transaction_id")...),
			mysql.Arg(s.PurchaseTransactionID),
		}})
	}

	if s.IntellectualPropertyID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "intellectual_property_id")...),
			mysql.Arg(s.IntellectualPropertyID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindPurchaseHistory retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPurchaseHistory(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*PurchaseHistory, error) {
	if len(cols) == 0 {
		return PurchaseHistories.Query(
			sm.Where(PurchaseHistories.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return PurchaseHistories.Query(
		sm.Where(PurchaseHistories.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(PurchaseHistories.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PurchaseHistoryExists checks the presence of a single record by primary key
func PurchaseHistoryExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return PurchaseHistories.Query(
		sm.Where(PurchaseHistories.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PurchaseHistory is retrieved from the database
func (o *PurchaseHistory) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PurchaseHistories.AfterSelectHooks.RunHooks(ctx, exec, PurchaseHistorySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PurchaseHistories.AfterInsertHooks.RunHooks(ctx, exec, PurchaseHistorySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PurchaseHistories.AfterUpdateHooks.RunHooks(ctx, exec, PurchaseHistorySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PurchaseHistories.AfterDeleteHooks.RunHooks(ctx, exec, PurchaseHistorySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the PurchaseHistory
func (o *PurchaseHistory) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *PurchaseHistory) pkEQ() dialect.Expression {
	return mysql.Quote("purchase_histories", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PurchaseHistory
func (o *PurchaseHistory) Update(ctx context.Context, exec bob.Executor, s *PurchaseHistorySetter) error {
	_, err := PurchaseHistories.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single PurchaseHistory record with an executor
func (o *PurchaseHistory) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PurchaseHistories.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PurchaseHistory using the executor
func (o *PurchaseHistory) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PurchaseHistories.Query(
		sm.Where(PurchaseHistories.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PurchaseHistorySlice is retrieved from the database
func (o PurchaseHistorySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PurchaseHistories.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PurchaseHistories.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PurchaseHistories.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PurchaseHistories.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PurchaseHistorySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("purchase_histories", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PurchaseHistorySlice) copyMatchingRows(from ...*PurchaseHistory) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PurchaseHistorySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PurchaseHistories.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PurchaseHistory:
				o.copyMatchingRows(retrieved)
			case []*PurchaseHistory:
				o.copyMatchingRows(retrieved...)
			case PurchaseHistorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PurchaseHistory or a slice of PurchaseHistory
				// then run the AfterUpdateHooks on the slice
				_, err = PurchaseHistories.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PurchaseHistorySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PurchaseHistories.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PurchaseHistory:
				o.copyMatchingRows(retrieved)
			case []*PurchaseHistory:
				o.copyMatchingRows(retrieved...)
			case PurchaseHistorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PurchaseHistory or a slice of PurchaseHistory
				// then run the AfterDeleteHooks on the slice
				_, err = PurchaseHistories.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PurchaseHistorySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PurchaseHistorySetter) error {
	_, err := PurchaseHistories.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o PurchaseHistorySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PurchaseHistories.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PurchaseHistorySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PurchaseHistories.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// PurchaseTransaction starts a query for related objects on purchase_transactions
func (o *PurchaseHistory) PurchaseTransaction(mods ...bob.Mod[*dialect.SelectQuery]) PurchaseTransactionsQuery {
	return PurchaseTransactions.Query(append(mods,
		sm.Where(PurchaseTransactions.Columns.ID.EQ(mysql.Arg(o.PurchaseTransactionID))),
	)...)
}

func (os PurchaseHistorySlice) PurchaseTransaction(mods ...bob.Mod[*dialect.SelectQuery]) PurchaseTransactionsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.PurchaseTransactionID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return PurchaseTransactions.Query(append(mods,
		sm.Where(mysql.Group(PurchaseTransactions.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// IntellectualProperty starts a query for related objects on intellectual_properties
func (o *PurchaseHistory) IntellectualProperty(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertiesQuery {
	return IntellectualProperties.Query(append(mods,
		sm.Where(IntellectualProperties.Columns.ID.EQ(mysql.Arg(o.IntellectualPropertyID))),
	)...)
}

func (os PurchaseHistorySlice) IntellectualProperty(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertiesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.IntellectualPropertyID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return IntellectualProperties.Query(append(mods,
		sm.Where(mysql.Group(IntellectualProperties.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachPurchaseHistoryPurchaseTransaction0(ctx context.Context, exec bob.Executor, count int, purchaseHistory0 *PurchaseHistory, purchaseTransaction1 *PurchaseTransaction) (*PurchaseHistory, error) {
	setter := &PurchaseHistorySetter{
		PurchaseTransactionID: omit.From(purchaseTransaction1.ID),
	}

	err := purchaseHistory0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPurchaseHistoryPurchaseTransaction0: %w", err)
	}

	return purchaseHistory0, nil
}

func (purchaseHistory0 *PurchaseHistory) InsertPurchaseTransaction(ctx context.Context, exec bob.Executor, related *PurchaseTransactionSetter) error {
	purchaseTransaction1, err := PurchaseTransactions.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPurchaseHistoryPurchaseTransaction0(ctx, exec, 1, purchaseHistory0, purchaseTransaction1)
	if err != nil {
		return err
	}

	purchaseHistory0.R.PurchaseTransaction = purchaseTransaction1

	purchaseTransaction1.R.PurchaseHistories = append(purchaseTransaction1.R.PurchaseHistories, purchaseHistory0)

	return nil
}

func (purchaseHistory0 *PurchaseHistory) AttachPurchaseTransaction(ctx context.Context, exec bob.Executor, purchaseTransaction1 *PurchaseTransaction) error {
	var err error

	_, err = attachPurchaseHistoryPurchaseTransaction0(ctx, exec, 1, purchaseHistory0, purchaseTransaction1)
	if err != nil {
		return err
	}

	purchaseHistory0.R.PurchaseTransaction = purchaseTransaction1

	purchaseTransaction1.R.PurchaseHistories = append(purchaseTransaction1.R.PurchaseHistories, purchaseHistory0)

	return nil
}

func attachPurchaseHistoryIntellectualProperty0(ctx context.Context, exec bob.Executor, count int, purchaseHistory0 *PurchaseHistory, intellectualProperty1 *IntellectualProperty) (*PurchaseHistory, error) {
	setter := &PurchaseHistorySetter{
		IntellectualPropertyID: omit.From(intellectualProperty1.ID),
	}

	err := purchaseHistory0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPurchaseHistoryIntellectualProperty0: %w", err)
	}

	return purchaseHistory0, nil
}

func (purchaseHistory0 *PurchaseHistory) InsertIntellectualProperty(ctx context.Context, exec bob.Executor, related *IntellectualPropertySetter) error {
	intellectualProperty1, err := IntellectualProperties.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPurchaseHistoryIntellectualProperty0(ctx, exec, 1, purchaseHistory0, intellectualProperty1)
	if err != nil {
		return err
	}

	purchaseHistory0.R.IntellectualProperty = intellectualProperty1

	intellectualProperty1.R.PurchaseHistories = append(intellectualProperty1.R.PurchaseHistories, purchaseHistory0)

	return nil
}

func (purchaseHistory0 *PurchaseHistory) AttachIntellectualProperty(ctx context.Context, exec bob.Executor, intellectualProperty1 *IntellectualProperty) error {
	var err error

	_, err = attachPurchaseHistoryIntellectualProperty0(ctx, exec, 1, purchaseHistory0, intellectualProperty1)
	if err != nil {
		return err
	}

	purchaseHistory0.R.IntellectualProperty = intellectualProperty1

	intellectualProperty1.R.PurchaseHistories = append(intellectualProperty1.R.PurchaseHistories, purchaseHistory0)

	return nil
}

type purchaseHistoryWhere[Q mysql.Filterable] struct {
	ID                     mysql.WhereMod[Q, string]
	PurchaseTransactionID  mysql.WhereMod[Q, string]
	IntellectualPropertyID mysql.WhereMod[Q, string]
	CreatedAt              mysql.WhereMod[Q, time.Time]
	UpdatedAt              mysql.WhereMod[Q, time.Time]
}

func (purchaseHistoryWhere[Q]) AliasedAs(alias string) purchaseHistoryWhere[Q] {
	return buildPurchaseHistoryWhere[Q](buildPurchaseHistoryColumns(alias))
}

func buildPurchaseHistoryWhere[Q mysql.Filterable](cols purchaseHistoryColumns) purchaseHistoryWhere[Q] {
	return purchaseHistoryWhere[Q]{
		ID:                     mysql.Where[Q, string](cols.ID),
		PurchaseTransactionID:  mysql.Where[Q, string](cols.PurchaseTransactionID),
		IntellectualPropertyID: mysql.Where[Q, string](cols.IntellectualPropertyID),
		CreatedAt:              mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:              mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *PurchaseHistory) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PurchaseTransaction":
		rel, ok := retrieved.(*PurchaseTransaction)
		if !ok {
			return fmt.Errorf("purchaseHistory cannot load %T as %q", retrieved, name)
		}

		o.R.PurchaseTransaction = rel

		if rel != nil {
			rel.R.PurchaseHistories = PurchaseHistorySlice{o}
		}
		return nil
	case "IntellectualProperty":
		rel, ok := retrieved.(*IntellectualProperty)
		if !ok {
			return fmt.Errorf("purchaseHistory cannot load %T as %q", retrieved, name)
		}

		o.R.IntellectualProperty = rel

		if rel != nil {
			rel.R.PurchaseHistories = PurchaseHistorySlice{o}
		}
		return nil
	default:
		return fmt.Errorf("purchaseHistory has no relationship %q", name)
	}
}

type purchaseHistoryPreloader struct {
	PurchaseTransaction  func(...mysql.PreloadOption) mysql.Preloader
	IntellectualProperty func(...mysql.PreloadOption) mysql.Preloader
}

func buildPurchaseHistoryPreloader() purchaseHistoryPreloader {
	return purchaseHistoryPreloader{
		PurchaseTransaction: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*PurchaseTransaction, PurchaseTransactionSlice](mysql.PreloadRel{
				Name: "PurchaseTransaction",
				Sides: []mysql.PreloadSide{
					{
						From:        PurchaseHistories,
						To:          PurchaseTransactions,
						FromColumns: []string{"purchase_transaction_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, PurchaseTransactions.Columns.Names(), opts...)
		},
		IntellectualProperty: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*IntellectualProperty, IntellectualPropertySlice](mysql.PreloadRel{
				Name: "IntellectualProperty",
				Sides: []mysql.PreloadSide{
					{
						From:        PurchaseHistories,
						To:          IntellectualProperties,
						FromColumns: []string{"intellectual_property_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, IntellectualProperties.Columns.Names(), opts...)
		},
	}
}

type purchaseHistoryThenLoader[Q orm.Loadable] struct {
	PurchaseTransaction  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	IntellectualProperty func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPurchaseHistoryThenLoader[Q orm.Loadable]() purchaseHistoryThenLoader[Q] {
	type PurchaseTransactionLoadInterface interface {
		LoadPurchaseTransaction(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type IntellectualPropertyLoadInterface interface {
		LoadIntellectualProperty(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return purchaseHistoryThenLoader[Q]{
		PurchaseTransaction: thenLoadBuilder[Q](
			"PurchaseTransaction",
			func(ctx context.Context, exec bob.Executor, retrieved PurchaseTransactionLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPurchaseTransaction(ctx, exec, mods...)
			},
		),
		IntellectualProperty: thenLoadBuilder[Q](
			"IntellectualProperty",
			func(ctx context.Context, exec bob.Executor, retrieved IntellectualPropertyLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadIntellectualProperty(ctx, exec, mods...)
			},
		),
	}
}

// LoadPurchaseTransaction loads the purchaseHistory's PurchaseTransaction into the .R struct
func (o *PurchaseHistory) LoadPurchaseTransaction(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PurchaseTransaction = nil

	related, err := o.PurchaseTransaction(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PurchaseHistories = PurchaseHistorySlice{o}

	o.R.PurchaseTransaction = related
	return nil
}

// LoadPurchaseTransaction loads the purchaseHistory's PurchaseTransaction into the .R struct
func (os PurchaseHistorySlice) LoadPurchaseTransaction(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	purchaseTransactions, err := os.PurchaseTransaction(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range purchaseTransactions {

			if !(o.PurchaseTransactionID == rel.ID) {
				continue
			}

			rel.R.PurchaseHistories = append(rel.R.PurchaseHistories, o)

			o.R.PurchaseTransaction = rel
			break
		}
	}

	return nil
}

// LoadIntellectualProperty loads the purchaseHistory's IntellectualProperty into the .R struct
func (o *PurchaseHistory) LoadIntellectualProperty(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IntellectualProperty = nil

	related, err := o.IntellectualProperty(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PurchaseHistories = PurchaseHistorySlice{o}

	o.R.IntellectualProperty = related
	return nil
}

// LoadIntellectualProperty loads the purchaseHistory's IntellectualProperty into the .R struct
func (os PurchaseHistorySlice) LoadIntellectualProperty(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	intellectualProperties, err := os.IntellectualProperty(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range intellectualProperties {

			if !(o.IntellectualPropertyID == rel.ID) {
				continue
			}

			rel.R.PurchaseHistories = append(rel.R.PurchaseHistories, o)

			o.R.IntellectualProperty = rel
			break
		}
	}

	return nil
}

type purchaseHistoryJoins[Q dialect.Joinable] struct {
	typ                  string
	PurchaseTransaction  modAs[Q, purchaseTransactionColumns]
	IntellectualProperty modAs[Q, intellectualPropertyColumns]
}

func (j purchaseHistoryJoins[Q]) aliasedAs(alias string) purchaseHistoryJoins[Q] {
	return buildPurchaseHistoryJoins[Q](buildPurchaseHistoryColumns(alias), j.typ)
}

func buildPurchaseHistoryJoins[Q dialect.Joinable](cols purchaseHistoryColumns, typ string) purchaseHistoryJoins[Q] {
	return purchaseHistoryJoins[Q]{
		typ: typ,
		PurchaseTransaction: modAs[Q, purchaseTransactionColumns]{
			c: PurchaseTransactions.Columns,
			f: func(to purchaseTransactionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PurchaseTransactions.Name().As(to.Alias())).On(
						to.ID.EQ(cols.PurchaseTransactionID),
					))
				}

				return mods
			},
		},
		IntellectualProperty: modAs[Q, intellectualPropertyColumns]{
			c: IntellectualProperties.Columns,
			f: func(to intellectualPropertyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, IntellectualProperties.Name().As(to.Alias())).On(
						to.ID.EQ(cols.IntellectualPropertyID),
					))
				}

				return mods
			},
		},
	}
}
