// Code generated by BobGen mysql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	enums "kujicole/infra/bob/enums"
)

// PurchaseTransaction is an object representing the database table.
type PurchaseTransaction struct {
	ID                    string                                  `db:"id,pk" `
	UserID                string                                  `db:"user_id" `
	IPCategoryID          string                                  `db:"ip_category_id" `
	PurchaseQuantity      int32                                   `db:"purchase_quantity" `
	PurchasePrice         decimal.Decimal                         `db:"purchase_price" `
	PaymentMethod         enums.PurchaseTransactionsPaymentMethod `db:"payment_method" `
	ProviderTransactionID null.Val[string]                        `db:"provider_transaction_id" `
	Status                enums.PurchaseTransactionsStatus        `db:"status" `
	PaidAt                null.Val[time.Time]                     `db:"paid_at" `
	CreatedAt             time.Time                               `db:"created_at" `
	UpdatedAt             time.Time                               `db:"updated_at" `

	R purchaseTransactionR `db:"-" `
}

// PurchaseTransactionSlice is an alias for a slice of pointers to PurchaseTransaction.
// This should almost always be used instead of []*PurchaseTransaction.
type PurchaseTransactionSlice []*PurchaseTransaction

// PurchaseTransactions contains methods to work with the purchase_transactions table
var PurchaseTransactions = mysql.NewTablex[*PurchaseTransaction, PurchaseTransactionSlice, *PurchaseTransactionSetter]("purchase_transactions", buildPurchaseTransactionColumns("purchase_transactions"), []string{"id"})

// PurchaseTransactionsQuery is a query on the purchase_transactions table
type PurchaseTransactionsQuery = *mysql.ViewQuery[*PurchaseTransaction, PurchaseTransactionSlice]

// purchaseTransactionR is where relationships are stored.
type purchaseTransactionR struct {
	PurchaseHistories                      PurchaseHistorySlice          // purchase_histories_ibfk_1
	User                                   *User                         // purchase_transactions_ibfk_1
	IPCategoryIntellectualPropertyCategory *IntellectualPropertyCategory // purchase_transactions_ibfk_2
}

func buildPurchaseTransactionColumns(alias string) purchaseTransactionColumns {
	return purchaseTransactionColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "ip_category_id", "purchase_quantity", "purchase_price", "payment_method", "provider_transaction_id", "status", "paid_at", "created_at", "updated_at",
		).WithParent("purchase_transactions"),
		tableAlias:            alias,
		ID:                    mysql.Quote(alias, "id"),
		UserID:                mysql.Quote(alias, "user_id"),
		IPCategoryID:          mysql.Quote(alias, "ip_category_id"),
		PurchaseQuantity:      mysql.Quote(alias, "purchase_quantity"),
		PurchasePrice:         mysql.Quote(alias, "purchase_price"),
		PaymentMethod:         mysql.Quote(alias, "payment_method"),
		ProviderTransactionID: mysql.Quote(alias, "provider_transaction_id"),
		Status:                mysql.Quote(alias, "status"),
		PaidAt:                mysql.Quote(alias, "paid_at"),
		CreatedAt:             mysql.Quote(alias, "created_at"),
		UpdatedAt:             mysql.Quote(alias, "updated_at"),
	}
}

type purchaseTransactionColumns struct {
	expr.ColumnsExpr
	tableAlias            string
	ID                    mysql.Expression
	UserID                mysql.Expression
	IPCategoryID          mysql.Expression
	PurchaseQuantity      mysql.Expression
	PurchasePrice         mysql.Expression
	PaymentMethod         mysql.Expression
	ProviderTransactionID mysql.Expression
	Status                mysql.Expression
	PaidAt                mysql.Expression
	CreatedAt             mysql.Expression
	UpdatedAt             mysql.Expression
}

func (c purchaseTransactionColumns) Alias() string {
	return c.tableAlias
}

func (purchaseTransactionColumns) AliasedAs(alias string) purchaseTransactionColumns {
	return buildPurchaseTransactionColumns(alias)
}

// PurchaseTransactionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PurchaseTransactionSetter struct {
	ID                    omit.Val[string]                                  `db:"id,pk" `
	UserID                omit.Val[string]                                  `db:"user_id" `
	IPCategoryID          omit.Val[string]                                  `db:"ip_category_id" `
	PurchaseQuantity      omit.Val[int32]                                   `db:"purchase_quantity" `
	PurchasePrice         omit.Val[decimal.Decimal]                         `db:"purchase_price" `
	PaymentMethod         omit.Val[enums.PurchaseTransactionsPaymentMethod] `db:"payment_method" `
	ProviderTransactionID omitnull.Val[string]                              `db:"provider_transaction_id" `
	Status                omit.Val[enums.PurchaseTransactionsStatus]        `db:"status" `
	PaidAt                omitnull.Val[time.Time]                           `db:"paid_at" `
	CreatedAt             omit.Val[time.Time]                               `db:"created_at" `
	UpdatedAt             omit.Val[time.Time]                               `db:"updated_at" `
}

func (s PurchaseTransactionSetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.IPCategoryID.IsValue() {
		vals = append(vals, "ip_category_id")
	}
	if s.PurchaseQuantity.IsValue() {
		vals = append(vals, "purchase_quantity")
	}
	if s.PurchasePrice.IsValue() {
		vals = append(vals, "purchase_price")
	}
	if s.PaymentMethod.IsValue() {
		vals = append(vals, "payment_method")
	}
	if !s.ProviderTransactionID.IsUnset() {
		vals = append(vals, "provider_transaction_id")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if !s.PaidAt.IsUnset() {
		vals = append(vals, "paid_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s PurchaseTransactionSetter) Overwrite(t *PurchaseTransaction) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.IPCategoryID.IsValue() {
		t.IPCategoryID = s.IPCategoryID.MustGet()
	}
	if s.PurchaseQuantity.IsValue() {
		t.PurchaseQuantity = s.PurchaseQuantity.MustGet()
	}
	if s.PurchasePrice.IsValue() {
		t.PurchasePrice = s.PurchasePrice.MustGet()
	}
	if s.PaymentMethod.IsValue() {
		t.PaymentMethod = s.PaymentMethod.MustGet()
	}
	if !s.ProviderTransactionID.IsUnset() {
		t.ProviderTransactionID = s.ProviderTransactionID.MustGetNull()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if !s.PaidAt.IsUnset() {
		t.PaidAt = s.PaidAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *PurchaseTransactionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PurchaseTransactions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UserID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UserID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IPCategoryID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IPCategoryID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.PurchaseQuantity.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PurchaseQuantity.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.PurchasePrice.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PurchasePrice.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.PaymentMethod.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PaymentMethod.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.ProviderTransactionID.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ProviderTransactionID.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Status.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Status.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.PaidAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PaidAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s PurchaseTransactionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("purchase_transactions")...)
}

func (s PurchaseTransactionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "user_id")...),
			mysql.Arg(s.UserID),
		}})
	}

	if s.IPCategoryID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "ip_category_id")...),
			mysql.Arg(s.IPCategoryID),
		}})
	}

	if s.PurchaseQuantity.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "purchase_quantity")...),
			mysql.Arg(s.PurchaseQuantity),
		}})
	}

	if s.PurchasePrice.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "purchase_price")...),
			mysql.Arg(s.PurchasePrice),
		}})
	}

	if s.PaymentMethod.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "payment_method")...),
			mysql.Arg(s.PaymentMethod),
		}})
	}

	if !s.ProviderTransactionID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "provider_transaction_id")...),
			mysql.Arg(s.ProviderTransactionID),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "status")...),
			mysql.Arg(s.Status),
		}})
	}

	if !s.PaidAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "paid_at")...),
			mysql.Arg(s.PaidAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindPurchaseTransaction retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPurchaseTransaction(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*PurchaseTransaction, error) {
	if len(cols) == 0 {
		return PurchaseTransactions.Query(
			sm.Where(PurchaseTransactions.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return PurchaseTransactions.Query(
		sm.Where(PurchaseTransactions.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(PurchaseTransactions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PurchaseTransactionExists checks the presence of a single record by primary key
func PurchaseTransactionExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return PurchaseTransactions.Query(
		sm.Where(PurchaseTransactions.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PurchaseTransaction is retrieved from the database
func (o *PurchaseTransaction) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PurchaseTransactions.AfterSelectHooks.RunHooks(ctx, exec, PurchaseTransactionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PurchaseTransactions.AfterInsertHooks.RunHooks(ctx, exec, PurchaseTransactionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PurchaseTransactions.AfterUpdateHooks.RunHooks(ctx, exec, PurchaseTransactionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PurchaseTransactions.AfterDeleteHooks.RunHooks(ctx, exec, PurchaseTransactionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the PurchaseTransaction
func (o *PurchaseTransaction) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *PurchaseTransaction) pkEQ() dialect.Expression {
	return mysql.Quote("purchase_transactions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PurchaseTransaction
func (o *PurchaseTransaction) Update(ctx context.Context, exec bob.Executor, s *PurchaseTransactionSetter) error {
	_, err := PurchaseTransactions.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single PurchaseTransaction record with an executor
func (o *PurchaseTransaction) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PurchaseTransactions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PurchaseTransaction using the executor
func (o *PurchaseTransaction) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PurchaseTransactions.Query(
		sm.Where(PurchaseTransactions.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PurchaseTransactionSlice is retrieved from the database
func (o PurchaseTransactionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PurchaseTransactions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PurchaseTransactions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PurchaseTransactions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PurchaseTransactions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PurchaseTransactionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("purchase_transactions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PurchaseTransactionSlice) copyMatchingRows(from ...*PurchaseTransaction) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PurchaseTransactionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PurchaseTransactions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PurchaseTransaction:
				o.copyMatchingRows(retrieved)
			case []*PurchaseTransaction:
				o.copyMatchingRows(retrieved...)
			case PurchaseTransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PurchaseTransaction or a slice of PurchaseTransaction
				// then run the AfterUpdateHooks on the slice
				_, err = PurchaseTransactions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PurchaseTransactionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PurchaseTransactions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PurchaseTransaction:
				o.copyMatchingRows(retrieved)
			case []*PurchaseTransaction:
				o.copyMatchingRows(retrieved...)
			case PurchaseTransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PurchaseTransaction or a slice of PurchaseTransaction
				// then run the AfterDeleteHooks on the slice
				_, err = PurchaseTransactions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PurchaseTransactionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PurchaseTransactionSetter) error {
	_, err := PurchaseTransactions.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o PurchaseTransactionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PurchaseTransactions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PurchaseTransactionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PurchaseTransactions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// PurchaseHistories starts a query for related objects on purchase_histories
func (o *PurchaseTransaction) PurchaseHistories(mods ...bob.Mod[*dialect.SelectQuery]) PurchaseHistoriesQuery {
	return PurchaseHistories.Query(append(mods,
		sm.Where(PurchaseHistories.Columns.PurchaseTransactionID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os PurchaseTransactionSlice) PurchaseHistories(mods ...bob.Mod[*dialect.SelectQuery]) PurchaseHistoriesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return PurchaseHistories.Query(append(mods,
		sm.Where(mysql.Group(PurchaseHistories.Columns.PurchaseTransactionID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *PurchaseTransaction) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(mysql.Arg(o.UserID))),
	)...)
}

func (os PurchaseTransactionSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.UserID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(mysql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// IPCategoryIntellectualPropertyCategory starts a query for related objects on intellectual_property_categories
func (o *PurchaseTransaction) IPCategoryIntellectualPropertyCategory(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertyCategoriesQuery {
	return IntellectualPropertyCategories.Query(append(mods,
		sm.Where(IntellectualPropertyCategories.Columns.ID.EQ(mysql.Arg(o.IPCategoryID))),
	)...)
}

func (os PurchaseTransactionSlice) IPCategoryIntellectualPropertyCategory(mods ...bob.Mod[*dialect.SelectQuery]) IntellectualPropertyCategoriesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.IPCategoryID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return IntellectualPropertyCategories.Query(append(mods,
		sm.Where(mysql.Group(IntellectualPropertyCategories.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertPurchaseTransactionPurchaseHistories0(ctx context.Context, exec bob.Executor, purchaseHistories1 []*PurchaseHistorySetter, purchaseTransaction0 *PurchaseTransaction) (PurchaseHistorySlice, error) {
	for i := range purchaseHistories1 {
		purchaseHistories1[i].PurchaseTransactionID = omit.From(purchaseTransaction0.ID)
	}

	ret, err := PurchaseHistories.Insert(bob.ToMods(purchaseHistories1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertPurchaseTransactionPurchaseHistories0: %w", err)
	}

	return ret, nil
}

func attachPurchaseTransactionPurchaseHistories0(ctx context.Context, exec bob.Executor, count int, purchaseHistories1 PurchaseHistorySlice, purchaseTransaction0 *PurchaseTransaction) (PurchaseHistorySlice, error) {
	setter := &PurchaseHistorySetter{
		PurchaseTransactionID: omit.From(purchaseTransaction0.ID),
	}

	err := purchaseHistories1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachPurchaseTransactionPurchaseHistories0: %w", err)
	}

	return purchaseHistories1, nil
}

func (purchaseTransaction0 *PurchaseTransaction) InsertPurchaseHistories(ctx context.Context, exec bob.Executor, related ...*PurchaseHistorySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	purchaseHistories1, err := insertPurchaseTransactionPurchaseHistories0(ctx, exec, related, purchaseTransaction0)
	if err != nil {
		return err
	}

	purchaseTransaction0.R.PurchaseHistories = append(purchaseTransaction0.R.PurchaseHistories, purchaseHistories1...)

	for _, rel := range purchaseHistories1 {
		rel.R.PurchaseTransaction = purchaseTransaction0
	}
	return nil
}

func (purchaseTransaction0 *PurchaseTransaction) AttachPurchaseHistories(ctx context.Context, exec bob.Executor, related ...*PurchaseHistory) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	purchaseHistories1 := PurchaseHistorySlice(related)

	_, err = attachPurchaseTransactionPurchaseHistories0(ctx, exec, len(related), purchaseHistories1, purchaseTransaction0)
	if err != nil {
		return err
	}

	purchaseTransaction0.R.PurchaseHistories = append(purchaseTransaction0.R.PurchaseHistories, purchaseHistories1...)

	for _, rel := range related {
		rel.R.PurchaseTransaction = purchaseTransaction0
	}

	return nil
}

func attachPurchaseTransactionUser0(ctx context.Context, exec bob.Executor, count int, purchaseTransaction0 *PurchaseTransaction, user1 *User) (*PurchaseTransaction, error) {
	setter := &PurchaseTransactionSetter{
		UserID: omit.From(user1.ID),
	}

	err := purchaseTransaction0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPurchaseTransactionUser0: %w", err)
	}

	return purchaseTransaction0, nil
}

func (purchaseTransaction0 *PurchaseTransaction) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPurchaseTransactionUser0(ctx, exec, 1, purchaseTransaction0, user1)
	if err != nil {
		return err
	}

	purchaseTransaction0.R.User = user1

	user1.R.PurchaseTransactions = append(user1.R.PurchaseTransactions, purchaseTransaction0)

	return nil
}

func (purchaseTransaction0 *PurchaseTransaction) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachPurchaseTransactionUser0(ctx, exec, 1, purchaseTransaction0, user1)
	if err != nil {
		return err
	}

	purchaseTransaction0.R.User = user1

	user1.R.PurchaseTransactions = append(user1.R.PurchaseTransactions, purchaseTransaction0)

	return nil
}

func attachPurchaseTransactionIPCategoryIntellectualPropertyCategory0(ctx context.Context, exec bob.Executor, count int, purchaseTransaction0 *PurchaseTransaction, intellectualPropertyCategory1 *IntellectualPropertyCategory) (*PurchaseTransaction, error) {
	setter := &PurchaseTransactionSetter{
		IPCategoryID: omit.From(intellectualPropertyCategory1.ID),
	}

	err := purchaseTransaction0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPurchaseTransactionIPCategoryIntellectualPropertyCategory0: %w", err)
	}

	return purchaseTransaction0, nil
}

func (purchaseTransaction0 *PurchaseTransaction) InsertIPCategoryIntellectualPropertyCategory(ctx context.Context, exec bob.Executor, related *IntellectualPropertyCategorySetter) error {
	intellectualPropertyCategory1, err := IntellectualPropertyCategories.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPurchaseTransactionIPCategoryIntellectualPropertyCategory0(ctx, exec, 1, purchaseTransaction0, intellectualPropertyCategory1)
	if err != nil {
		return err
	}

	purchaseTransaction0.R.IPCategoryIntellectualPropertyCategory = intellectualPropertyCategory1

	intellectualPropertyCategory1.R.IPCategoryPurchaseTransactions = append(intellectualPropertyCategory1.R.IPCategoryPurchaseTransactions, purchaseTransaction0)

	return nil
}

func (purchaseTransaction0 *PurchaseTransaction) AttachIPCategoryIntellectualPropertyCategory(ctx context.Context, exec bob.Executor, intellectualPropertyCategory1 *IntellectualPropertyCategory) error {
	var err error

	_, err = attachPurchaseTransactionIPCategoryIntellectualPropertyCategory0(ctx, exec, 1, purchaseTransaction0, intellectualPropertyCategory1)
	if err != nil {
		return err
	}

	purchaseTransaction0.R.IPCategoryIntellectualPropertyCategory = intellectualPropertyCategory1

	intellectualPropertyCategory1.R.IPCategoryPurchaseTransactions = append(intellectualPropertyCategory1.R.IPCategoryPurchaseTransactions, purchaseTransaction0)

	return nil
}

type purchaseTransactionWhere[Q mysql.Filterable] struct {
	ID                    mysql.WhereMod[Q, string]
	UserID                mysql.WhereMod[Q, string]
	IPCategoryID          mysql.WhereMod[Q, string]
	PurchaseQuantity      mysql.WhereMod[Q, int32]
	PurchasePrice         mysql.WhereMod[Q, decimal.Decimal]
	PaymentMethod         mysql.WhereMod[Q, enums.PurchaseTransactionsPaymentMethod]
	ProviderTransactionID mysql.WhereNullMod[Q, string]
	Status                mysql.WhereMod[Q, enums.PurchaseTransactionsStatus]
	PaidAt                mysql.WhereNullMod[Q, time.Time]
	CreatedAt             mysql.WhereMod[Q, time.Time]
	UpdatedAt             mysql.WhereMod[Q, time.Time]
}

func (purchaseTransactionWhere[Q]) AliasedAs(alias string) purchaseTransactionWhere[Q] {
	return buildPurchaseTransactionWhere[Q](buildPurchaseTransactionColumns(alias))
}

func buildPurchaseTransactionWhere[Q mysql.Filterable](cols purchaseTransactionColumns) purchaseTransactionWhere[Q] {
	return purchaseTransactionWhere[Q]{
		ID:                    mysql.Where[Q, string](cols.ID),
		UserID:                mysql.Where[Q, string](cols.UserID),
		IPCategoryID:          mysql.Where[Q, string](cols.IPCategoryID),
		PurchaseQuantity:      mysql.Where[Q, int32](cols.PurchaseQuantity),
		PurchasePrice:         mysql.Where[Q, decimal.Decimal](cols.PurchasePrice),
		PaymentMethod:         mysql.Where[Q, enums.PurchaseTransactionsPaymentMethod](cols.PaymentMethod),
		ProviderTransactionID: mysql.WhereNull[Q, string](cols.ProviderTransactionID),
		Status:                mysql.Where[Q, enums.PurchaseTransactionsStatus](cols.Status),
		PaidAt:                mysql.WhereNull[Q, time.Time](cols.PaidAt),
		CreatedAt:             mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:             mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *PurchaseTransaction) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PurchaseHistories":
		rels, ok := retrieved.(PurchaseHistorySlice)
		if !ok {
			return fmt.Errorf("purchaseTransaction cannot load %T as %q", retrieved, name)
		}

		o.R.PurchaseHistories = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.PurchaseTransaction = o
			}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("purchaseTransaction cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.PurchaseTransactions = PurchaseTransactionSlice{o}
		}
		return nil
	case "IPCategoryIntellectualPropertyCategory":
		rel, ok := retrieved.(*IntellectualPropertyCategory)
		if !ok {
			return fmt.Errorf("purchaseTransaction cannot load %T as %q", retrieved, name)
		}

		o.R.IPCategoryIntellectualPropertyCategory = rel

		if rel != nil {
			rel.R.IPCategoryPurchaseTransactions = PurchaseTransactionSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("purchaseTransaction has no relationship %q", name)
	}
}

type purchaseTransactionPreloader struct {
	User                                   func(...mysql.PreloadOption) mysql.Preloader
	IPCategoryIntellectualPropertyCategory func(...mysql.PreloadOption) mysql.Preloader
}

func buildPurchaseTransactionPreloader() purchaseTransactionPreloader {
	return purchaseTransactionPreloader{
		User: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*User, UserSlice](mysql.PreloadRel{
				Name: "User",
				Sides: []mysql.PreloadSide{
					{
						From:        PurchaseTransactions,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
		IPCategoryIntellectualPropertyCategory: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*IntellectualPropertyCategory, IntellectualPropertyCategorySlice](mysql.PreloadRel{
				Name: "IPCategoryIntellectualPropertyCategory",
				Sides: []mysql.PreloadSide{
					{
						From:        PurchaseTransactions,
						To:          IntellectualPropertyCategories,
						FromColumns: []string{"ip_category_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, IntellectualPropertyCategories.Columns.Names(), opts...)
		},
	}
}

type purchaseTransactionThenLoader[Q orm.Loadable] struct {
	PurchaseHistories                      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User                                   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	IPCategoryIntellectualPropertyCategory func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPurchaseTransactionThenLoader[Q orm.Loadable]() purchaseTransactionThenLoader[Q] {
	type PurchaseHistoriesLoadInterface interface {
		LoadPurchaseHistories(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type IPCategoryIntellectualPropertyCategoryLoadInterface interface {
		LoadIPCategoryIntellectualPropertyCategory(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return purchaseTransactionThenLoader[Q]{
		PurchaseHistories: thenLoadBuilder[Q](
			"PurchaseHistories",
			func(ctx context.Context, exec bob.Executor, retrieved PurchaseHistoriesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPurchaseHistories(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
		IPCategoryIntellectualPropertyCategory: thenLoadBuilder[Q](
			"IPCategoryIntellectualPropertyCategory",
			func(ctx context.Context, exec bob.Executor, retrieved IPCategoryIntellectualPropertyCategoryLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadIPCategoryIntellectualPropertyCategory(ctx, exec, mods...)
			},
		),
	}
}

// LoadPurchaseHistories loads the purchaseTransaction's PurchaseHistories into the .R struct
func (o *PurchaseTransaction) LoadPurchaseHistories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PurchaseHistories = nil

	related, err := o.PurchaseHistories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.PurchaseTransaction = o
	}

	o.R.PurchaseHistories = related
	return nil
}

// LoadPurchaseHistories loads the purchaseTransaction's PurchaseHistories into the .R struct
func (os PurchaseTransactionSlice) LoadPurchaseHistories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	purchaseHistories, err := os.PurchaseHistories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.PurchaseHistories = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range purchaseHistories {

			if !(o.ID == rel.PurchaseTransactionID) {
				continue
			}

			rel.R.PurchaseTransaction = o

			o.R.PurchaseHistories = append(o.R.PurchaseHistories, rel)
		}
	}

	return nil
}

// LoadUser loads the purchaseTransaction's User into the .R struct
func (o *PurchaseTransaction) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PurchaseTransactions = PurchaseTransactionSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the purchaseTransaction's User into the .R struct
func (os PurchaseTransactionSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.PurchaseTransactions = append(rel.R.PurchaseTransactions, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

// LoadIPCategoryIntellectualPropertyCategory loads the purchaseTransaction's IPCategoryIntellectualPropertyCategory into the .R struct
func (o *PurchaseTransaction) LoadIPCategoryIntellectualPropertyCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IPCategoryIntellectualPropertyCategory = nil

	related, err := o.IPCategoryIntellectualPropertyCategory(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.IPCategoryPurchaseTransactions = PurchaseTransactionSlice{o}

	o.R.IPCategoryIntellectualPropertyCategory = related
	return nil
}

// LoadIPCategoryIntellectualPropertyCategory loads the purchaseTransaction's IPCategoryIntellectualPropertyCategory into the .R struct
func (os PurchaseTransactionSlice) LoadIPCategoryIntellectualPropertyCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	intellectualPropertyCategories, err := os.IPCategoryIntellectualPropertyCategory(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range intellectualPropertyCategories {

			if !(o.IPCategoryID == rel.ID) {
				continue
			}

			rel.R.IPCategoryPurchaseTransactions = append(rel.R.IPCategoryPurchaseTransactions, o)

			o.R.IPCategoryIntellectualPropertyCategory = rel
			break
		}
	}

	return nil
}

type purchaseTransactionJoins[Q dialect.Joinable] struct {
	typ                                    string
	PurchaseHistories                      modAs[Q, purchaseHistoryColumns]
	User                                   modAs[Q, userColumns]
	IPCategoryIntellectualPropertyCategory modAs[Q, intellectualPropertyCategoryColumns]
}

func (j purchaseTransactionJoins[Q]) aliasedAs(alias string) purchaseTransactionJoins[Q] {
	return buildPurchaseTransactionJoins[Q](buildPurchaseTransactionColumns(alias), j.typ)
}

func buildPurchaseTransactionJoins[Q dialect.Joinable](cols purchaseTransactionColumns, typ string) purchaseTransactionJoins[Q] {
	return purchaseTransactionJoins[Q]{
		typ: typ,
		PurchaseHistories: modAs[Q, purchaseHistoryColumns]{
			c: PurchaseHistories.Columns,
			f: func(to purchaseHistoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PurchaseHistories.Name().As(to.Alias())).On(
						to.PurchaseTransactionID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
		IPCategoryIntellectualPropertyCategory: modAs[Q, intellectualPropertyCategoryColumns]{
			c: IntellectualPropertyCategories.Columns,
			f: func(to intellectualPropertyCategoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, IntellectualPropertyCategories.Name().As(to.Alias())).On(
						to.ID.EQ(cols.IPCategoryID),
					))
				}

				return mods
			},
		},
	}
}
