// Code generated by BobGen mysql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// RefreshToken is an object representing the database table.
type RefreshToken struct {
	ID        string    `db:"id,pk" `
	UserID    string    `db:"user_id" `
	TokenHash string    `db:"token_hash" `
	ExpiresAt time.Time `db:"expires_at" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R refreshTokenR `db:"-" `
}

// RefreshTokenSlice is an alias for a slice of pointers to RefreshToken.
// This should almost always be used instead of []*RefreshToken.
type RefreshTokenSlice []*RefreshToken

// RefreshTokens contains methods to work with the refresh_tokens table
var RefreshTokens = mysql.NewTablex[*RefreshToken, RefreshTokenSlice, *RefreshTokenSetter]("refresh_tokens", buildRefreshTokenColumns("refresh_tokens"), []string{"id"}, []string{"user_id"})

// RefreshTokensQuery is a query on the refresh_tokens table
type RefreshTokensQuery = *mysql.ViewQuery[*RefreshToken, RefreshTokenSlice]

// refreshTokenR is where relationships are stored.
type refreshTokenR struct {
	User *User // refresh_tokens_ibfk_1
}

func buildRefreshTokenColumns(alias string) refreshTokenColumns {
	return refreshTokenColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "token_hash", "expires_at", "created_at", "updated_at",
		).WithParent("refresh_tokens"),
		tableAlias: alias,
		ID:         mysql.Quote(alias, "id"),
		UserID:     mysql.Quote(alias, "user_id"),
		TokenHash:  mysql.Quote(alias, "token_hash"),
		ExpiresAt:  mysql.Quote(alias, "expires_at"),
		CreatedAt:  mysql.Quote(alias, "created_at"),
		UpdatedAt:  mysql.Quote(alias, "updated_at"),
	}
}

type refreshTokenColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         mysql.Expression
	UserID     mysql.Expression
	TokenHash  mysql.Expression
	ExpiresAt  mysql.Expression
	CreatedAt  mysql.Expression
	UpdatedAt  mysql.Expression
}

func (c refreshTokenColumns) Alias() string {
	return c.tableAlias
}

func (refreshTokenColumns) AliasedAs(alias string) refreshTokenColumns {
	return buildRefreshTokenColumns(alias)
}

// RefreshTokenSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RefreshTokenSetter struct {
	ID        omit.Val[string]    `db:"id,pk" `
	UserID    omit.Val[string]    `db:"user_id" `
	TokenHash omit.Val[string]    `db:"token_hash" `
	ExpiresAt omit.Val[time.Time] `db:"expires_at" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s RefreshTokenSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.TokenHash.IsValue() {
		vals = append(vals, "token_hash")
	}
	if s.ExpiresAt.IsValue() {
		vals = append(vals, "expires_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s RefreshTokenSetter) Overwrite(t *RefreshToken) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.TokenHash.IsValue() {
		t.TokenHash = s.TokenHash.MustGet()
	}
	if s.ExpiresAt.IsValue() {
		t.ExpiresAt = s.ExpiresAt.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *RefreshTokenSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RefreshTokens.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UserID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UserID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.TokenHash.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.TokenHash.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ExpiresAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ExpiresAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s RefreshTokenSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("refresh_tokens")...)
}

func (s RefreshTokenSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "user_id")...),
			mysql.Arg(s.UserID),
		}})
	}

	if s.TokenHash.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "token_hash")...),
			mysql.Arg(s.TokenHash),
		}})
	}

	if s.ExpiresAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "expires_at")...),
			mysql.Arg(s.ExpiresAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindRefreshToken retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRefreshToken(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*RefreshToken, error) {
	if len(cols) == 0 {
		return RefreshTokens.Query(
			sm.Where(RefreshTokens.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return RefreshTokens.Query(
		sm.Where(RefreshTokens.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(RefreshTokens.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RefreshTokenExists checks the presence of a single record by primary key
func RefreshTokenExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return RefreshTokens.Query(
		sm.Where(RefreshTokens.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RefreshToken is retrieved from the database
func (o *RefreshToken) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RefreshTokens.AfterSelectHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RefreshTokens.AfterInsertHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RefreshTokens.AfterUpdateHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RefreshTokens.AfterDeleteHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the RefreshToken
func (o *RefreshToken) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *RefreshToken) pkEQ() dialect.Expression {
	return mysql.Quote("refresh_tokens", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RefreshToken
func (o *RefreshToken) Update(ctx context.Context, exec bob.Executor, s *RefreshTokenSetter) error {
	_, err := RefreshTokens.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single RefreshToken record with an executor
func (o *RefreshToken) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RefreshTokens.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RefreshToken using the executor
func (o *RefreshToken) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RefreshTokens.Query(
		sm.Where(RefreshTokens.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RefreshTokenSlice is retrieved from the database
func (o RefreshTokenSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RefreshTokens.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RefreshTokens.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RefreshTokens.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RefreshTokens.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o RefreshTokenSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("refresh_tokens", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RefreshTokenSlice) copyMatchingRows(from ...*RefreshToken) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RefreshTokenSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RefreshTokens.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RefreshToken:
				o.copyMatchingRows(retrieved)
			case []*RefreshToken:
				o.copyMatchingRows(retrieved...)
			case RefreshTokenSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RefreshToken or a slice of RefreshToken
				// then run the AfterUpdateHooks on the slice
				_, err = RefreshTokens.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RefreshTokenSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RefreshTokens.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RefreshToken:
				o.copyMatchingRows(retrieved)
			case []*RefreshToken:
				o.copyMatchingRows(retrieved...)
			case RefreshTokenSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RefreshToken or a slice of RefreshToken
				// then run the AfterDeleteHooks on the slice
				_, err = RefreshTokens.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RefreshTokenSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RefreshTokenSetter) error {
	_, err := RefreshTokens.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o RefreshTokenSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RefreshTokens.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RefreshTokenSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RefreshTokens.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *RefreshToken) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(mysql.Arg(o.UserID))),
	)...)
}

func (os RefreshTokenSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.UserID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(mysql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachRefreshTokenUser0(ctx context.Context, exec bob.Executor, count int, refreshToken0 *RefreshToken, user1 *User) (*RefreshToken, error) {
	setter := &RefreshTokenSetter{
		UserID: omit.From(user1.ID),
	}

	err := refreshToken0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachRefreshTokenUser0: %w", err)
	}

	return refreshToken0, nil
}

func (refreshToken0 *RefreshToken) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachRefreshTokenUser0(ctx, exec, 1, refreshToken0, user1)
	if err != nil {
		return err
	}

	refreshToken0.R.User = user1

	user1.R.RefreshToken = refreshToken0

	return nil
}

func (refreshToken0 *RefreshToken) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachRefreshTokenUser0(ctx, exec, 1, refreshToken0, user1)
	if err != nil {
		return err
	}

	refreshToken0.R.User = user1

	user1.R.RefreshToken = refreshToken0

	return nil
}

type refreshTokenWhere[Q mysql.Filterable] struct {
	ID        mysql.WhereMod[Q, string]
	UserID    mysql.WhereMod[Q, string]
	TokenHash mysql.WhereMod[Q, string]
	ExpiresAt mysql.WhereMod[Q, time.Time]
	CreatedAt mysql.WhereMod[Q, time.Time]
	UpdatedAt mysql.WhereMod[Q, time.Time]
}

func (refreshTokenWhere[Q]) AliasedAs(alias string) refreshTokenWhere[Q] {
	return buildRefreshTokenWhere[Q](buildRefreshTokenColumns(alias))
}

func buildRefreshTokenWhere[Q mysql.Filterable](cols refreshTokenColumns) refreshTokenWhere[Q] {
	return refreshTokenWhere[Q]{
		ID:        mysql.Where[Q, string](cols.ID),
		UserID:    mysql.Where[Q, string](cols.UserID),
		TokenHash: mysql.Where[Q, string](cols.TokenHash),
		ExpiresAt: mysql.Where[Q, time.Time](cols.ExpiresAt),
		CreatedAt: mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *RefreshToken) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("refreshToken cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.RefreshToken = o
		}
		return nil
	default:
		return fmt.Errorf("refreshToken has no relationship %q", name)
	}
}

type refreshTokenPreloader struct {
	User func(...mysql.PreloadOption) mysql.Preloader
}

func buildRefreshTokenPreloader() refreshTokenPreloader {
	return refreshTokenPreloader{
		User: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*User, UserSlice](mysql.PreloadRel{
				Name: "User",
				Sides: []mysql.PreloadSide{
					{
						From:        RefreshTokens,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type refreshTokenThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildRefreshTokenThenLoader[Q orm.Loadable]() refreshTokenThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return refreshTokenThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the refreshToken's User into the .R struct
func (o *RefreshToken) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.RefreshToken = o

	o.R.User = related
	return nil
}

// LoadUser loads the refreshToken's User into the .R struct
func (os RefreshTokenSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.RefreshToken = o

			o.R.User = rel
			break
		}
	}

	return nil
}

type refreshTokenJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j refreshTokenJoins[Q]) aliasedAs(alias string) refreshTokenJoins[Q] {
	return buildRefreshTokenJoins[Q](buildRefreshTokenColumns(alias), j.typ)
}

func buildRefreshTokenJoins[Q dialect.Joinable](cols refreshTokenColumns, typ string) refreshTokenJoins[Q] {
	return refreshTokenJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
