// Code generated by BobGen mysql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// ShippingAddress is an object representing the database table.
type ShippingAddress struct {
	ID            string           `db:"id,pk" `
	UserID        string           `db:"user_id" `
	RecipientName string           `db:"recipient_name" `
	PhoneNumber   string           `db:"phone_number" `
	PostCode      string           `db:"post_code" `
	Prefecture    string           `db:"prefecture" `
	Address1      string           `db:"address_1" `
	Address2      null.Val[string] `db:"address_2" `
	ApartmentName null.Val[string] `db:"apartment_name" `
	CreatedAt     time.Time        `db:"created_at" `
	UpdatedAt     time.Time        `db:"updated_at" `

	R shippingAddressR `db:"-" `
}

// ShippingAddressSlice is an alias for a slice of pointers to ShippingAddress.
// This should almost always be used instead of []*ShippingAddress.
type ShippingAddressSlice []*ShippingAddress

// ShippingAddresses contains methods to work with the shipping_addresses table
var ShippingAddresses = mysql.NewTablex[*ShippingAddress, ShippingAddressSlice, *ShippingAddressSetter]("shipping_addresses", buildShippingAddressColumns("shipping_addresses"), []string{"id"})

// ShippingAddressesQuery is a query on the shipping_addresses table
type ShippingAddressesQuery = *mysql.ViewQuery[*ShippingAddress, ShippingAddressSlice]

// shippingAddressR is where relationships are stored.
type shippingAddressR struct {
	User *User // shipping_addresses_ibfk_1
}

func buildShippingAddressColumns(alias string) shippingAddressColumns {
	return shippingAddressColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "recipient_name", "phone_number", "post_code", "prefecture", "address_1", "address_2", "apartment_name", "created_at", "updated_at",
		).WithParent("shipping_addresses"),
		tableAlias:    alias,
		ID:            mysql.Quote(alias, "id"),
		UserID:        mysql.Quote(alias, "user_id"),
		RecipientName: mysql.Quote(alias, "recipient_name"),
		PhoneNumber:   mysql.Quote(alias, "phone_number"),
		PostCode:      mysql.Quote(alias, "post_code"),
		Prefecture:    mysql.Quote(alias, "prefecture"),
		Address1:      mysql.Quote(alias, "address_1"),
		Address2:      mysql.Quote(alias, "address_2"),
		ApartmentName: mysql.Quote(alias, "apartment_name"),
		CreatedAt:     mysql.Quote(alias, "created_at"),
		UpdatedAt:     mysql.Quote(alias, "updated_at"),
	}
}

type shippingAddressColumns struct {
	expr.ColumnsExpr
	tableAlias    string
	ID            mysql.Expression
	UserID        mysql.Expression
	RecipientName mysql.Expression
	PhoneNumber   mysql.Expression
	PostCode      mysql.Expression
	Prefecture    mysql.Expression
	Address1      mysql.Expression
	Address2      mysql.Expression
	ApartmentName mysql.Expression
	CreatedAt     mysql.Expression
	UpdatedAt     mysql.Expression
}

func (c shippingAddressColumns) Alias() string {
	return c.tableAlias
}

func (shippingAddressColumns) AliasedAs(alias string) shippingAddressColumns {
	return buildShippingAddressColumns(alias)
}

// ShippingAddressSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ShippingAddressSetter struct {
	ID            omit.Val[string]     `db:"id,pk" `
	UserID        omit.Val[string]     `db:"user_id" `
	RecipientName omit.Val[string]     `db:"recipient_name" `
	PhoneNumber   omit.Val[string]     `db:"phone_number" `
	PostCode      omit.Val[string]     `db:"post_code" `
	Prefecture    omit.Val[string]     `db:"prefecture" `
	Address1      omit.Val[string]     `db:"address_1" `
	Address2      omitnull.Val[string] `db:"address_2" `
	ApartmentName omitnull.Val[string] `db:"apartment_name" `
	CreatedAt     omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt     omit.Val[time.Time]  `db:"updated_at" `
}

func (s ShippingAddressSetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.RecipientName.IsValue() {
		vals = append(vals, "recipient_name")
	}
	if s.PhoneNumber.IsValue() {
		vals = append(vals, "phone_number")
	}
	if s.PostCode.IsValue() {
		vals = append(vals, "post_code")
	}
	if s.Prefecture.IsValue() {
		vals = append(vals, "prefecture")
	}
	if s.Address1.IsValue() {
		vals = append(vals, "address_1")
	}
	if !s.Address2.IsUnset() {
		vals = append(vals, "address_2")
	}
	if !s.ApartmentName.IsUnset() {
		vals = append(vals, "apartment_name")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ShippingAddressSetter) Overwrite(t *ShippingAddress) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.RecipientName.IsValue() {
		t.RecipientName = s.RecipientName.MustGet()
	}
	if s.PhoneNumber.IsValue() {
		t.PhoneNumber = s.PhoneNumber.MustGet()
	}
	if s.PostCode.IsValue() {
		t.PostCode = s.PostCode.MustGet()
	}
	if s.Prefecture.IsValue() {
		t.Prefecture = s.Prefecture.MustGet()
	}
	if s.Address1.IsValue() {
		t.Address1 = s.Address1.MustGet()
	}
	if !s.Address2.IsUnset() {
		t.Address2 = s.Address2.MustGetNull()
	}
	if !s.ApartmentName.IsUnset() {
		t.ApartmentName = s.ApartmentName.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ShippingAddressSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ShippingAddresses.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UserID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UserID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.RecipientName.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.RecipientName.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.PhoneNumber.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PhoneNumber.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.PostCode.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PostCode.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Prefecture.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Prefecture.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Address1.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Address1.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.Address2.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Address2.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.ApartmentName.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ApartmentName.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s ShippingAddressSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("shipping_addresses")...)
}

func (s ShippingAddressSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "user_id")...),
			mysql.Arg(s.UserID),
		}})
	}

	if s.RecipientName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "recipient_name")...),
			mysql.Arg(s.RecipientName),
		}})
	}

	if s.PhoneNumber.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "phone_number")...),
			mysql.Arg(s.PhoneNumber),
		}})
	}

	if s.PostCode.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "post_code")...),
			mysql.Arg(s.PostCode),
		}})
	}

	if s.Prefecture.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "prefecture")...),
			mysql.Arg(s.Prefecture),
		}})
	}

	if s.Address1.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "address_1")...),
			mysql.Arg(s.Address1),
		}})
	}

	if !s.Address2.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "address_2")...),
			mysql.Arg(s.Address2),
		}})
	}

	if !s.ApartmentName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "apartment_name")...),
			mysql.Arg(s.ApartmentName),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindShippingAddress retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindShippingAddress(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*ShippingAddress, error) {
	if len(cols) == 0 {
		return ShippingAddresses.Query(
			sm.Where(ShippingAddresses.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ShippingAddresses.Query(
		sm.Where(ShippingAddresses.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(ShippingAddresses.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ShippingAddressExists checks the presence of a single record by primary key
func ShippingAddressExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return ShippingAddresses.Query(
		sm.Where(ShippingAddresses.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ShippingAddress is retrieved from the database
func (o *ShippingAddress) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ShippingAddresses.AfterSelectHooks.RunHooks(ctx, exec, ShippingAddressSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ShippingAddresses.AfterInsertHooks.RunHooks(ctx, exec, ShippingAddressSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ShippingAddresses.AfterUpdateHooks.RunHooks(ctx, exec, ShippingAddressSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ShippingAddresses.AfterDeleteHooks.RunHooks(ctx, exec, ShippingAddressSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ShippingAddress
func (o *ShippingAddress) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *ShippingAddress) pkEQ() dialect.Expression {
	return mysql.Quote("shipping_addresses", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ShippingAddress
func (o *ShippingAddress) Update(ctx context.Context, exec bob.Executor, s *ShippingAddressSetter) error {
	_, err := ShippingAddresses.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single ShippingAddress record with an executor
func (o *ShippingAddress) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ShippingAddresses.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ShippingAddress using the executor
func (o *ShippingAddress) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ShippingAddresses.Query(
		sm.Where(ShippingAddresses.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ShippingAddressSlice is retrieved from the database
func (o ShippingAddressSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ShippingAddresses.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ShippingAddresses.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ShippingAddresses.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ShippingAddresses.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ShippingAddressSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("shipping_addresses", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ShippingAddressSlice) copyMatchingRows(from ...*ShippingAddress) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ShippingAddressSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ShippingAddresses.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ShippingAddress:
				o.copyMatchingRows(retrieved)
			case []*ShippingAddress:
				o.copyMatchingRows(retrieved...)
			case ShippingAddressSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ShippingAddress or a slice of ShippingAddress
				// then run the AfterUpdateHooks on the slice
				_, err = ShippingAddresses.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ShippingAddressSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ShippingAddresses.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ShippingAddress:
				o.copyMatchingRows(retrieved)
			case []*ShippingAddress:
				o.copyMatchingRows(retrieved...)
			case ShippingAddressSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ShippingAddress or a slice of ShippingAddress
				// then run the AfterDeleteHooks on the slice
				_, err = ShippingAddresses.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ShippingAddressSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ShippingAddressSetter) error {
	_, err := ShippingAddresses.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o ShippingAddressSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ShippingAddresses.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ShippingAddressSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ShippingAddresses.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *ShippingAddress) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(mysql.Arg(o.UserID))),
	)...)
}

func (os ShippingAddressSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.UserID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(mysql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachShippingAddressUser0(ctx context.Context, exec bob.Executor, count int, shippingAddress0 *ShippingAddress, user1 *User) (*ShippingAddress, error) {
	setter := &ShippingAddressSetter{
		UserID: omit.From(user1.ID),
	}

	err := shippingAddress0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachShippingAddressUser0: %w", err)
	}

	return shippingAddress0, nil
}

func (shippingAddress0 *ShippingAddress) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachShippingAddressUser0(ctx, exec, 1, shippingAddress0, user1)
	if err != nil {
		return err
	}

	shippingAddress0.R.User = user1

	user1.R.ShippingAddresses = append(user1.R.ShippingAddresses, shippingAddress0)

	return nil
}

func (shippingAddress0 *ShippingAddress) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachShippingAddressUser0(ctx, exec, 1, shippingAddress0, user1)
	if err != nil {
		return err
	}

	shippingAddress0.R.User = user1

	user1.R.ShippingAddresses = append(user1.R.ShippingAddresses, shippingAddress0)

	return nil
}

type shippingAddressWhere[Q mysql.Filterable] struct {
	ID            mysql.WhereMod[Q, string]
	UserID        mysql.WhereMod[Q, string]
	RecipientName mysql.WhereMod[Q, string]
	PhoneNumber   mysql.WhereMod[Q, string]
	PostCode      mysql.WhereMod[Q, string]
	Prefecture    mysql.WhereMod[Q, string]
	Address1      mysql.WhereMod[Q, string]
	Address2      mysql.WhereNullMod[Q, string]
	ApartmentName mysql.WhereNullMod[Q, string]
	CreatedAt     mysql.WhereMod[Q, time.Time]
	UpdatedAt     mysql.WhereMod[Q, time.Time]
}

func (shippingAddressWhere[Q]) AliasedAs(alias string) shippingAddressWhere[Q] {
	return buildShippingAddressWhere[Q](buildShippingAddressColumns(alias))
}

func buildShippingAddressWhere[Q mysql.Filterable](cols shippingAddressColumns) shippingAddressWhere[Q] {
	return shippingAddressWhere[Q]{
		ID:            mysql.Where[Q, string](cols.ID),
		UserID:        mysql.Where[Q, string](cols.UserID),
		RecipientName: mysql.Where[Q, string](cols.RecipientName),
		PhoneNumber:   mysql.Where[Q, string](cols.PhoneNumber),
		PostCode:      mysql.Where[Q, string](cols.PostCode),
		Prefecture:    mysql.Where[Q, string](cols.Prefecture),
		Address1:      mysql.Where[Q, string](cols.Address1),
		Address2:      mysql.WhereNull[Q, string](cols.Address2),
		ApartmentName: mysql.WhereNull[Q, string](cols.ApartmentName),
		CreatedAt:     mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:     mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *ShippingAddress) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("shippingAddress cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.ShippingAddresses = ShippingAddressSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("shippingAddress has no relationship %q", name)
	}
}

type shippingAddressPreloader struct {
	User func(...mysql.PreloadOption) mysql.Preloader
}

func buildShippingAddressPreloader() shippingAddressPreloader {
	return shippingAddressPreloader{
		User: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*User, UserSlice](mysql.PreloadRel{
				Name: "User",
				Sides: []mysql.PreloadSide{
					{
						From:        ShippingAddresses,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type shippingAddressThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildShippingAddressThenLoader[Q orm.Loadable]() shippingAddressThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return shippingAddressThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the shippingAddress's User into the .R struct
func (o *ShippingAddress) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ShippingAddresses = ShippingAddressSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the shippingAddress's User into the .R struct
func (os ShippingAddressSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.ShippingAddresses = append(rel.R.ShippingAddresses, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type shippingAddressJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j shippingAddressJoins[Q]) aliasedAs(alias string) shippingAddressJoins[Q] {
	return buildShippingAddressJoins[Q](buildShippingAddressColumns(alias), j.typ)
}

func buildShippingAddressJoins[Q dialect.Joinable](cols shippingAddressColumns, typ string) shippingAddressJoins[Q] {
	return shippingAddressJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
