// Code generated by BobGen mysql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	enums "kujicole/infra/bob/enums"
)

// User is an object representing the database table.
type User struct {
	ID             string            `db:"id,pk" `
	MailAddress    string            `db:"mail_address" `
	Nickname       string            `db:"nickname" `
	PasswordHash   string            `db:"password_hash" `
	Birthdate      time.Time         `db:"birthdate" `
	Gender         enums.UsersGender `db:"gender" `
	IsAdmin        bool              `db:"is_admin" `
	IsMailmagazine bool              `db:"is_mailmagazine" `
	CreatedAt      time.Time         `db:"created_at" `
	UpdatedAt      time.Time         `db:"updated_at" `

	R userR `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = mysql.NewTablex[*User, UserSlice, *UserSetter]("users", buildUserColumns("users"), []string{"id"})

// UsersQuery is a query on the users table
type UsersQuery = *mysql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	Contacts          ContactSlice         // contacts_ibfk_1
	CreditCards       CreditCardSlice      // credit_cards_ibfk_1
	RefreshToken      *RefreshToken        // refresh_tokens_ibfk_1
	ShippingAddresses ShippingAddressSlice // shipping_addresses_ibfk_1
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "mail_address", "nickname", "password_hash", "birthdate", "gender", "is_admin", "is_mailmagazine", "created_at", "updated_at",
		).WithParent("users"),
		tableAlias:     alias,
		ID:             mysql.Quote(alias, "id"),
		MailAddress:    mysql.Quote(alias, "mail_address"),
		Nickname:       mysql.Quote(alias, "nickname"),
		PasswordHash:   mysql.Quote(alias, "password_hash"),
		Birthdate:      mysql.Quote(alias, "birthdate"),
		Gender:         mysql.Quote(alias, "gender"),
		IsAdmin:        mysql.Quote(alias, "is_admin"),
		IsMailmagazine: mysql.Quote(alias, "is_mailmagazine"),
		CreatedAt:      mysql.Quote(alias, "created_at"),
		UpdatedAt:      mysql.Quote(alias, "updated_at"),
	}
}

type userColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             mysql.Expression
	MailAddress    mysql.Expression
	Nickname       mysql.Expression
	PasswordHash   mysql.Expression
	Birthdate      mysql.Expression
	Gender         mysql.Expression
	IsAdmin        mysql.Expression
	IsMailmagazine mysql.Expression
	CreatedAt      mysql.Expression
	UpdatedAt      mysql.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID             omit.Val[string]            `db:"id,pk" `
	MailAddress    omit.Val[string]            `db:"mail_address" `
	Nickname       omit.Val[string]            `db:"nickname" `
	PasswordHash   omit.Val[string]            `db:"password_hash" `
	Birthdate      omit.Val[time.Time]         `db:"birthdate" `
	Gender         omit.Val[enums.UsersGender] `db:"gender" `
	IsAdmin        omit.Val[bool]              `db:"is_admin" `
	IsMailmagazine omit.Val[bool]              `db:"is_mailmagazine" `
	CreatedAt      omit.Val[time.Time]         `db:"created_at" `
	UpdatedAt      omit.Val[time.Time]         `db:"updated_at" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.MailAddress.IsValue() {
		vals = append(vals, "mail_address")
	}
	if s.Nickname.IsValue() {
		vals = append(vals, "nickname")
	}
	if s.PasswordHash.IsValue() {
		vals = append(vals, "password_hash")
	}
	if s.Birthdate.IsValue() {
		vals = append(vals, "birthdate")
	}
	if s.Gender.IsValue() {
		vals = append(vals, "gender")
	}
	if s.IsAdmin.IsValue() {
		vals = append(vals, "is_admin")
	}
	if s.IsMailmagazine.IsValue() {
		vals = append(vals, "is_mailmagazine")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.MailAddress.IsValue() {
		t.MailAddress = s.MailAddress.MustGet()
	}
	if s.Nickname.IsValue() {
		t.Nickname = s.Nickname.MustGet()
	}
	if s.PasswordHash.IsValue() {
		t.PasswordHash = s.PasswordHash.MustGet()
	}
	if s.Birthdate.IsValue() {
		t.Birthdate = s.Birthdate.MustGet()
	}
	if s.Gender.IsValue() {
		t.Gender = s.Gender.MustGet()
	}
	if s.IsAdmin.IsValue() {
		t.IsAdmin = s.IsAdmin.MustGet()
	}
	if s.IsMailmagazine.IsValue() {
		t.IsMailmagazine = s.IsMailmagazine.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.MailAddress.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.MailAddress.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Nickname.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Nickname.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.PasswordHash.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PasswordHash.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Birthdate.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Birthdate.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Gender.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Gender.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IsAdmin.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IsAdmin.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IsMailmagazine.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IsMailmagazine.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("users")...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.MailAddress.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "mail_address")...),
			mysql.Arg(s.MailAddress),
		}})
	}

	if s.Nickname.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "nickname")...),
			mysql.Arg(s.Nickname),
		}})
	}

	if s.PasswordHash.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "password_hash")...),
			mysql.Arg(s.PasswordHash),
		}})
	}

	if s.Birthdate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "birthdate")...),
			mysql.Arg(s.Birthdate),
		}})
	}

	if s.Gender.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "gender")...),
			mysql.Arg(s.Gender),
		}})
	}

	if s.IsAdmin.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "is_admin")...),
			mysql.Arg(s.IsAdmin),
		}})
	}

	if s.IsMailmagazine.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "is_mailmagazine")...),
			mysql.Arg(s.IsMailmagazine),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			sm.Where(Users.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Users.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return mysql.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	_, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		sm.Where(Users.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Contacts starts a query for related objects on contacts
func (o *User) Contacts(mods ...bob.Mod[*dialect.SelectQuery]) ContactsQuery {
	return Contacts.Query(append(mods,
		sm.Where(Contacts.Columns.UserID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Contacts(mods ...bob.Mod[*dialect.SelectQuery]) ContactsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Contacts.Query(append(mods,
		sm.Where(mysql.Group(Contacts.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// CreditCards starts a query for related objects on credit_cards
func (o *User) CreditCards(mods ...bob.Mod[*dialect.SelectQuery]) CreditCardsQuery {
	return CreditCards.Query(append(mods,
		sm.Where(CreditCards.Columns.UserID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os UserSlice) CreditCards(mods ...bob.Mod[*dialect.SelectQuery]) CreditCardsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return CreditCards.Query(append(mods,
		sm.Where(mysql.Group(CreditCards.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// RefreshToken starts a query for related objects on refresh_tokens
func (o *User) RefreshToken(mods ...bob.Mod[*dialect.SelectQuery]) RefreshTokensQuery {
	return RefreshTokens.Query(append(mods,
		sm.Where(RefreshTokens.Columns.UserID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os UserSlice) RefreshToken(mods ...bob.Mod[*dialect.SelectQuery]) RefreshTokensQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return RefreshTokens.Query(append(mods,
		sm.Where(mysql.Group(RefreshTokens.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// ShippingAddresses starts a query for related objects on shipping_addresses
func (o *User) ShippingAddresses(mods ...bob.Mod[*dialect.SelectQuery]) ShippingAddressesQuery {
	return ShippingAddresses.Query(append(mods,
		sm.Where(ShippingAddresses.Columns.UserID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os UserSlice) ShippingAddresses(mods ...bob.Mod[*dialect.SelectQuery]) ShippingAddressesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return ShippingAddresses.Query(append(mods,
		sm.Where(mysql.Group(ShippingAddresses.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

func insertUserContacts0(ctx context.Context, exec bob.Executor, contacts1 []*ContactSetter, user0 *User) (ContactSlice, error) {
	for i := range contacts1 {
		contacts1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Contacts.Insert(bob.ToMods(contacts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserContacts0: %w", err)
	}

	return ret, nil
}

func attachUserContacts0(ctx context.Context, exec bob.Executor, count int, contacts1 ContactSlice, user0 *User) (ContactSlice, error) {
	setter := &ContactSetter{
		UserID: omit.From(user0.ID),
	}

	err := contacts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserContacts0: %w", err)
	}

	return contacts1, nil
}

func (user0 *User) InsertContacts(ctx context.Context, exec bob.Executor, related ...*ContactSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	contacts1, err := insertUserContacts0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Contacts = append(user0.R.Contacts, contacts1...)

	for _, rel := range contacts1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachContacts(ctx context.Context, exec bob.Executor, related ...*Contact) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	contacts1 := ContactSlice(related)

	_, err = attachUserContacts0(ctx, exec, len(related), contacts1, user0)
	if err != nil {
		return err
	}

	user0.R.Contacts = append(user0.R.Contacts, contacts1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserCreditCards0(ctx context.Context, exec bob.Executor, creditCards1 []*CreditCardSetter, user0 *User) (CreditCardSlice, error) {
	for i := range creditCards1 {
		creditCards1[i].UserID = omit.From(user0.ID)
	}

	ret, err := CreditCards.Insert(bob.ToMods(creditCards1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserCreditCards0: %w", err)
	}

	return ret, nil
}

func attachUserCreditCards0(ctx context.Context, exec bob.Executor, count int, creditCards1 CreditCardSlice, user0 *User) (CreditCardSlice, error) {
	setter := &CreditCardSetter{
		UserID: omit.From(user0.ID),
	}

	err := creditCards1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserCreditCards0: %w", err)
	}

	return creditCards1, nil
}

func (user0 *User) InsertCreditCards(ctx context.Context, exec bob.Executor, related ...*CreditCardSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	creditCards1, err := insertUserCreditCards0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.CreditCards = append(user0.R.CreditCards, creditCards1...)

	for _, rel := range creditCards1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachCreditCards(ctx context.Context, exec bob.Executor, related ...*CreditCard) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	creditCards1 := CreditCardSlice(related)

	_, err = attachUserCreditCards0(ctx, exec, len(related), creditCards1, user0)
	if err != nil {
		return err
	}

	user0.R.CreditCards = append(user0.R.CreditCards, creditCards1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserRefreshToken0(ctx context.Context, exec bob.Executor, refreshToken1 *RefreshTokenSetter, user0 *User) (*RefreshToken, error) {
	refreshToken1.UserID = omit.From(user0.ID)

	ret, err := RefreshTokens.Insert(refreshToken1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserRefreshToken0: %w", err)
	}

	return ret, nil
}

func attachUserRefreshToken0(ctx context.Context, exec bob.Executor, count int, refreshToken1 *RefreshToken, user0 *User) (*RefreshToken, error) {
	setter := &RefreshTokenSetter{
		UserID: omit.From(user0.ID),
	}

	err := refreshToken1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserRefreshToken0: %w", err)
	}

	return refreshToken1, nil
}

func (user0 *User) InsertRefreshToken(ctx context.Context, exec bob.Executor, related *RefreshTokenSetter) error {
	refreshToken1, err := insertUserRefreshToken0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.RefreshToken = refreshToken1

	refreshToken1.R.User = user0

	return nil
}

func (user0 *User) AttachRefreshToken(ctx context.Context, exec bob.Executor, refreshToken1 *RefreshToken) error {
	var err error

	_, err = attachUserRefreshToken0(ctx, exec, 1, refreshToken1, user0)
	if err != nil {
		return err
	}

	user0.R.RefreshToken = refreshToken1

	refreshToken1.R.User = user0

	return nil
}

func insertUserShippingAddresses0(ctx context.Context, exec bob.Executor, shippingAddresses1 []*ShippingAddressSetter, user0 *User) (ShippingAddressSlice, error) {
	for i := range shippingAddresses1 {
		shippingAddresses1[i].UserID = omit.From(user0.ID)
	}

	ret, err := ShippingAddresses.Insert(bob.ToMods(shippingAddresses1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserShippingAddresses0: %w", err)
	}

	return ret, nil
}

func attachUserShippingAddresses0(ctx context.Context, exec bob.Executor, count int, shippingAddresses1 ShippingAddressSlice, user0 *User) (ShippingAddressSlice, error) {
	setter := &ShippingAddressSetter{
		UserID: omit.From(user0.ID),
	}

	err := shippingAddresses1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserShippingAddresses0: %w", err)
	}

	return shippingAddresses1, nil
}

func (user0 *User) InsertShippingAddresses(ctx context.Context, exec bob.Executor, related ...*ShippingAddressSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	shippingAddresses1, err := insertUserShippingAddresses0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.ShippingAddresses = append(user0.R.ShippingAddresses, shippingAddresses1...)

	for _, rel := range shippingAddresses1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachShippingAddresses(ctx context.Context, exec bob.Executor, related ...*ShippingAddress) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	shippingAddresses1 := ShippingAddressSlice(related)

	_, err = attachUserShippingAddresses0(ctx, exec, len(related), shippingAddresses1, user0)
	if err != nil {
		return err
	}

	user0.R.ShippingAddresses = append(user0.R.ShippingAddresses, shippingAddresses1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

type userWhere[Q mysql.Filterable] struct {
	ID             mysql.WhereMod[Q, string]
	MailAddress    mysql.WhereMod[Q, string]
	Nickname       mysql.WhereMod[Q, string]
	PasswordHash   mysql.WhereMod[Q, string]
	Birthdate      mysql.WhereMod[Q, time.Time]
	Gender         mysql.WhereMod[Q, enums.UsersGender]
	IsAdmin        mysql.WhereMod[Q, bool]
	IsMailmagazine mysql.WhereMod[Q, bool]
	CreatedAt      mysql.WhereMod[Q, time.Time]
	UpdatedAt      mysql.WhereMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q mysql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:             mysql.Where[Q, string](cols.ID),
		MailAddress:    mysql.Where[Q, string](cols.MailAddress),
		Nickname:       mysql.Where[Q, string](cols.Nickname),
		PasswordHash:   mysql.Where[Q, string](cols.PasswordHash),
		Birthdate:      mysql.Where[Q, time.Time](cols.Birthdate),
		Gender:         mysql.Where[Q, enums.UsersGender](cols.Gender),
		IsAdmin:        mysql.Where[Q, bool](cols.IsAdmin),
		IsMailmagazine: mysql.Where[Q, bool](cols.IsMailmagazine),
		CreatedAt:      mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:      mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Contacts":
		rels, ok := retrieved.(ContactSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Contacts = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "CreditCards":
		rels, ok := retrieved.(CreditCardSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.CreditCards = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "RefreshToken":
		rel, ok := retrieved.(*RefreshToken)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.RefreshToken = rel

		if rel != nil {
			rel.R.User = o
		}
		return nil
	case "ShippingAddresses":
		rels, ok := retrieved.(ShippingAddressSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.ShippingAddresses = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct {
	RefreshToken func(...mysql.PreloadOption) mysql.Preloader
}

func buildUserPreloader() userPreloader {
	return userPreloader{
		RefreshToken: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*RefreshToken, RefreshTokenSlice](mysql.PreloadRel{
				Name: "RefreshToken",
				Sides: []mysql.PreloadSide{
					{
						From:        Users,
						To:          RefreshTokens,
						FromColumns: []string{"id"},
						ToColumns:   []string{"user_id"},
					},
				},
			}, RefreshTokens.Columns.Names(), opts...)
		},
	}
}

type userThenLoader[Q orm.Loadable] struct {
	Contacts          func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CreditCards       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	RefreshToken      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ShippingAddresses func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type ContactsLoadInterface interface {
		LoadContacts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CreditCardsLoadInterface interface {
		LoadCreditCards(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type RefreshTokenLoadInterface interface {
		LoadRefreshToken(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ShippingAddressesLoadInterface interface {
		LoadShippingAddresses(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		Contacts: thenLoadBuilder[Q](
			"Contacts",
			func(ctx context.Context, exec bob.Executor, retrieved ContactsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadContacts(ctx, exec, mods...)
			},
		),
		CreditCards: thenLoadBuilder[Q](
			"CreditCards",
			func(ctx context.Context, exec bob.Executor, retrieved CreditCardsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreditCards(ctx, exec, mods...)
			},
		),
		RefreshToken: thenLoadBuilder[Q](
			"RefreshToken",
			func(ctx context.Context, exec bob.Executor, retrieved RefreshTokenLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadRefreshToken(ctx, exec, mods...)
			},
		),
		ShippingAddresses: thenLoadBuilder[Q](
			"ShippingAddresses",
			func(ctx context.Context, exec bob.Executor, retrieved ShippingAddressesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadShippingAddresses(ctx, exec, mods...)
			},
		),
	}
}

// LoadContacts loads the user's Contacts into the .R struct
func (o *User) LoadContacts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Contacts = nil

	related, err := o.Contacts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Contacts = related
	return nil
}

// LoadContacts loads the user's Contacts into the .R struct
func (os UserSlice) LoadContacts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	contacts, err := os.Contacts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Contacts = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range contacts {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Contacts = append(o.R.Contacts, rel)
		}
	}

	return nil
}

// LoadCreditCards loads the user's CreditCards into the .R struct
func (o *User) LoadCreditCards(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreditCards = nil

	related, err := o.CreditCards(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.CreditCards = related
	return nil
}

// LoadCreditCards loads the user's CreditCards into the .R struct
func (os UserSlice) LoadCreditCards(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	creditCards, err := os.CreditCards(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.CreditCards = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range creditCards {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.CreditCards = append(o.R.CreditCards, rel)
		}
	}

	return nil
}

// LoadRefreshToken loads the user's RefreshToken into the .R struct
func (o *User) LoadRefreshToken(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.RefreshToken = nil

	related, err := o.RefreshToken(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.User = o

	o.R.RefreshToken = related
	return nil
}

// LoadRefreshToken loads the user's RefreshToken into the .R struct
func (os UserSlice) LoadRefreshToken(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	refreshTokens, err := os.RefreshToken(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range refreshTokens {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.RefreshToken = rel
			break
		}
	}

	return nil
}

// LoadShippingAddresses loads the user's ShippingAddresses into the .R struct
func (o *User) LoadShippingAddresses(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ShippingAddresses = nil

	related, err := o.ShippingAddresses(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.ShippingAddresses = related
	return nil
}

// LoadShippingAddresses loads the user's ShippingAddresses into the .R struct
func (os UserSlice) LoadShippingAddresses(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	shippingAddresses, err := os.ShippingAddresses(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ShippingAddresses = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range shippingAddresses {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.ShippingAddresses = append(o.R.ShippingAddresses, rel)
		}
	}

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ               string
	Contacts          modAs[Q, contactColumns]
	CreditCards       modAs[Q, creditCardColumns]
	RefreshToken      modAs[Q, refreshTokenColumns]
	ShippingAddresses modAs[Q, shippingAddressColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		Contacts: modAs[Q, contactColumns]{
			c: Contacts.Columns,
			f: func(to contactColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Contacts.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		CreditCards: modAs[Q, creditCardColumns]{
			c: CreditCards.Columns,
			f: func(to creditCardColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, CreditCards.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		RefreshToken: modAs[Q, refreshTokenColumns]{
			c: RefreshTokens.Columns,
			f: func(to refreshTokenColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, RefreshTokens.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		ShippingAddresses: modAs[Q, shippingAddressColumns]{
			c: ShippingAddresses.Columns,
			f: func(to shippingAddressColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ShippingAddresses.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
