// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CheckStockInput struct {
	IPCategoryID ID  `json:"ipCategoryId"`
	DrawCount    int `json:"drawCount"`
}

type CheckStockResult struct {
	IsStockAvailable bool `json:"isStockAvailable"`
}

type DrawIntellectualPropertyInput struct {
	IPCategoryID ID  `json:"ipCategoryId"`
	DrawCount    int `json:"drawCount"`
}

type IntellectualProperty struct {
	ID            ID        `json:"id"`
	IPRankGroupID ID        `json:"ipRankGroupId"`
	Name          string    `json:"name"`
	Stock         int       `json:"stock"`
	IsHidden      bool      `json:"isHidden"`
	ImgURL        *string   `json:"imgUrl,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type IntellectualPropertyCategory struct {
	ID             ID                               `json:"id"`
	Name           string                           `json:"name"`
	Price          float64                          `json:"price"`
	SalesStartDate time.Time                        `json:"salesStartDate"`
	SalesEndDate   time.Time                        `json:"salesEndDate"`
	Fee            float64                          `json:"fee"`
	Precautions    *string                          `json:"precautions,omitempty"`
	IsHidden       bool                             `json:"isHidden"`
	ImgURL         *string                          `json:"imgUrl,omitempty"`
	CreatedAt      time.Time                        `json:"createdAt"`
	UpdatedAt      time.Time                        `json:"updatedAt"`
	RankGroups     []*IntellectualPropertyRankGroup `json:"rankGroups,omitempty"`
}

type IntellectualPropertyRankGroup struct {
	ID           ID                       `json:"id"`
	IPCategoryID ID                       `json:"ip_category_id"`
	Name         string                   `json:"name"`
	Rank         IntellectualPropertyRank `json:"rank"`
	EmissionRate int                      `json:"emissionRate"`
	Explanation  *string                  `json:"explanation,omitempty"`
	IsHidden     bool                     `json:"isHidden"`
	Comments     *string                  `json:"comments,omitempty"`
	ImgURL       *string                  `json:"imgUrl,omitempty"`
	CreatedAt    time.Time                `json:"createdAt"`
	UpdatedAt    time.Time                `json:"updatedAt"`
	Properties   []*IntellectualProperty  `json:"properties"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID             ID        `json:"id"`
	Nickname       string    `json:"nickname"`
	Password       string    `json:"password"`
	Birthdate      time.Time `json:"birthdate"`
	Gender         Gender    `json:"gender"`
	IsAdmin        bool      `json:"isAdmin"`
	IsMailmagazine bool      `json:"isMailmagazine"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type Gender string

const (
	GenderMale   Gender = "male"
	GenderFemale Gender = "female"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Gender) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Gender) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IntellectualPropertyRank string

const (
	IntellectualPropertyRankS IntellectualPropertyRank = "S"
	IntellectualPropertyRankA IntellectualPropertyRank = "A"
	IntellectualPropertyRankB IntellectualPropertyRank = "B"
	IntellectualPropertyRankC IntellectualPropertyRank = "C"
	IntellectualPropertyRankD IntellectualPropertyRank = "D"
	IntellectualPropertyRankE IntellectualPropertyRank = "E"
)

var AllIntellectualPropertyRank = []IntellectualPropertyRank{
	IntellectualPropertyRankS,
	IntellectualPropertyRankA,
	IntellectualPropertyRankB,
	IntellectualPropertyRankC,
	IntellectualPropertyRankD,
	IntellectualPropertyRankE,
}

func (e IntellectualPropertyRank) IsValid() bool {
	switch e {
	case IntellectualPropertyRankS, IntellectualPropertyRankA, IntellectualPropertyRankB, IntellectualPropertyRankC, IntellectualPropertyRankD, IntellectualPropertyRankE:
		return true
	}
	return false
}

func (e IntellectualPropertyRank) String() string {
	return string(e)
}

func (e *IntellectualPropertyRank) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IntellectualPropertyRank(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IntellectualPropertyRank", str)
	}
	return nil
}

func (e IntellectualPropertyRank) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IntellectualPropertyRank) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IntellectualPropertyRank) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
